client/controllers/userEvent.coffee, client/controllers/userEvents.coffee, client/views/userEvent.jade, collections/userEvents.coffee
The event details page now includes user name and date information for the creation and last modification of the event. The event table also includes the modification date.
=> Create audit trail for events

client/controllers/eventMap.coffee, client/controllers/map.coffee, client/controllers/mapFilters.coffee, client/router.coffee, client/stylesheets/event.import.styl, client/stylesheets/header.import.styl, client/views/eventMap.jade, client/views/userEvent.jade, collections/geolocations.coffee, collections/userEvents.coffee
I repurposed the event map code so that it works with tracked events.  I added a map to the event details page as well as plotted all locations on the map under the Event Map menu option. The event map currently doesn't handle plotting multiple events at the same location, so you'll only see one of the events. We may need a clustering plugin for leaflet to take care of that.
=> Create an Event Map for EIDR Connect

client/views/userEvent.jade
I removed the log in form from the articles section and fixed up some of the styling.
=> When EIDR C user not logged in, the articles area has a log in form

client/controllers/mapFilters.coffee, client/views/header.jade
I'm pretty sure I was seeing empty maps on the event pages when I shouldn't have, but things seemed to straighten out after I made a branch and checked it out. Please comment on whether you see event locations plotted on the map when an event has locations.
Otherwise, I brought back the event map menu option and fixed filtering it by event name.
=> Event map is not showing up on master branch

.meteor/packages, .meteor/versions, client/controllers/article.coffee, client/controllers/articles.coffee, client/router.coffee, client/views/userEvent.jade, collections/articles.coffee, collections/geolocations.coffee, collections/userEvents.coffee
I added a field to the article form for including the publication date of the article.  While I was in that area of the code, I also included some auditing information and updated the event's last modified fields when articles and locations are added.
=> Users can select article publication dates

client/controllers/userEvent.coffee, client/stylesheets/event.import.styl, client/views/layout.jade, client/views/userEvent.jade
I had a really hard time trying to fit the share link in without the page looking messy. I rearranged things so that the edit, save, and cancel buttons are at the very top of the page and a share button is now where the edit buttons used to be. Clicking the share button opens a panel where the user can copy the page's url.
=> Display event URL at top of event page with suggestion to link to it

client/controllers/map.coffee, client/views/userEvent.jade
The map is now hidden when the event has no locations.
=> Hide EIDR C event page map when there are no locations

client/controllers/adminUser.coffee, client/stylesheets/header.import.styl, client/toastr.coffee, collections/allUsers.coffee
* Display toast messages during the account creation process.
=> Account creation notification

client/controllers/adminUser.coffee, client/controllers/articles.coffee, client/stylesheets/_main.styl, client/stylesheets/about.import.styl, client/stylesheets/event.import.styl, client/stylesheets/events.import.styl, client/stylesheets/map.import.styl, client/stylesheets/toastr.import.styl, client/toastr.coffee, client/views/contactUs.jade, client/views/createAccount.jade, client/views/mapFilters.jade, client/views/userEvent.jade, client/views/userEvents.jade
add external link icons to article anchors
fix spacing between some elements
adjust the toast container, make toasts disappear after 10 seconds
other minor UI improvements
=> improve the UI

client/controllers/count.coffee, client/controllers/counts.coffee, client/controllers/geolocations.coffee, client/router.coffee, client/views/userEvent.jade, collections/articles.coffee, collections/counts.coffee, collections/userEvents.coffee
* Created a Case/Death Count module for the event.
* Allow 1 or more articles per count
=> Case death counts

client/controllers/articles.coffee, client/controllers/counts.coffee, client/views/userEvent.jade, collections/counts.coffee
While I was working with the case count article input, I made it a single select field since we don't really want multiple articles associated with one case count right now. I kept the url field an array in the counts collection so we don't have to update any existing data.
=> case count source articles can be selected from the list of existing articles

client/controllers/eventMap.coffee, client/stylesheets/eventMap.import.styl, client/stylesheets/globals.import.styl, client/views/eventMap.jade, imports/ui/mapMarkers.coffee
I limited the map to 5 events at a time and ordered them by creation date, so the most recent events will be at the top of the legend. The legend has buttons to view older and newer events and can be collapsed down in case it gets in the way of any map markers.
=> Add legend to map

client/controllers/userEvent.coffee, client/stylesheets/event.import.styl, client/views/userEvent.jade, collections/userEvents.coffee
I didn't add a disease field to the new event form because I'm thinking that if we do any autocomplete/diagnosis in the future, it will probably be based on the articles which are added to the event and these can't be added on the new event form. I had trouble deciding where to place the disease on the event page. I think it looks rather out of place as is.
=> Events can have a disease associated with them

client/controllers/articles.coffee, client/views/userEvent.jade, collections/articles.coffee, server/interfaces.coffee
improve the way we trigger the bootstrap calendar plugin
cache the date response from the promed server
=> add timezone field to the article form, misc improvements

client/controllers/eventMap.coffee, client/controllers/map.coffee, client/controllers/userEvent.coffee, client/router.coffee, client/views/userEvent.jade, collections/counts.coffee
I updated the event map and event page map to plot locations from incident reports rather than the location collection.
=> Show locations from incident reports on map

client/controllers/incidentReport.coffee, client/controllers/incidentReports.coffee, client/controllers/userEvent.coffee, client/views/incidentReports.jade, collections/counts.coffee
The species field is a non-required field and it's only displayed in the details section if it was entered.
=> Add species field to incident report form

collections/incidents.coffee
I added a startup method that splits incident reports with both case and death counts into 2 incidents.
=> Update db to split case/death counts into separate incidents

client/controllers/incidentReports.coffee, client/controllers/userEvent.coffee, client/views/incidentReports.jade, client/views/userEvent.jade
The order of the tabs has been switched and the extra columns added to the incident reports table.
=> Make incident report table the default tab and change columns

client/controllers/userEvents.coffee, client/views/userEvent.jade, collections/articles.coffee, collections/userEvents.coffee
I tried to get this to work without adding an extra field to the event collection but it just wouldn't work out. So I went ahead and added a field that holds the article count which gets updated when articles are added and deleted.
=> Add article count column to tracked events table

client/controllers/article.coffee, collections/articles.coffee
I added a toastr error message that displays when attempting to delete an article that has associated incident reports and updated the confirmation message when an article can be deleted.
=> Update article deletion

client/stylesheets/about.import.styl, client/stylesheets/comments.import.styl, client/stylesheets/curator.import.styl, client/stylesheets/download.import.styl, client/stylesheets/event-icons.import.styl, client/stylesheets/event.import.styl, client/stylesheets/eventMap.import.styl, client/stylesheets/events.import.styl, client/stylesheets/extends.import.styl, client/stylesheets/footer.import.styl, client/stylesheets/globals.import.styl, client/stylesheets/header.import.styl, client/stylesheets/map.import.styl, client/stylesheets/mapFilters.import.styl, client/stylesheets/mixins.import.styl, client/stylesheets/variables.import.styl
Preprends stylus variables with `$`.
Cleans up stylus — removes commas from lists of selectors.
=> Stylus variables

client/stylesheets/buttons.import.styl, client/stylesheets/globals.import.styl, client/stylesheets/variables.import.styl
I missed a few variables in the merge of #72, sorry about that!
=> Prepend variables in button stylesheet

.meteor/packages, .meteor/versions, client/controllers/incidentForm.coffee, client/controllers/incidentReport.coffee, client/controllers/incidentReports.coffee, client/stylesheets/_main.styl, client/stylesheets/dateRangePicker.import.styl, client/stylesheets/event.import.styl, client/stylesheets/events.import.styl, client/stylesheets/globals.import.styl, client/views/incidentForm.jade, client/views/incidentReports.jade, client/views/inlineDateRangePicker.jade, client/views/userEvent.jade, collections/incidents.coffee, imports/schemas/incidentReport.coffee, imports/ui/helpers.coffee, imports/ui/inlineDateRangePicker.coffee, imports/utils.coffee
The mockup shows an inline calendar for selecting the date ranges. The best date range library I found doesn't have an inline option but I was able to make it work. I made a fork of the original library to add the option but the feature isn't complete yet.
=> Change incident dates to datetime ranges

client/controllers/sourceModal.coffee, client/stylesheets/_main.styl, client/stylesheets/datepicker.import.styl, client/views/sourceModal.jade
The date picker is now inline and the time selector has been separated into its own input.
=> Use expanded date selector for source dates

client/controllers/eventMap.coffee, client/views/mapFilters.jade, imports/stylesheets/eventMap.import.styl
Reduces items in event map list to 8 from 10.
Also tweaks layout on wide screens.
=> Reduce number of event list items and improve styling

client/controllers/suggestedIncidents.coffee, client/views/suggestedIncidentModal.jade, imports/stylesheets/datepicker.import.styl, imports/stylesheets/event.import.styl
I went with displaying a specified number of characters before and after the incident link text. While testing, I noticed that dates for the suggested incidents aren't being set properly on the form. I thought it would be a quick fix and took a look at it but I don't understand the date territories well enough.
=> Show article snippets in incident suggestion modal

client/controllers/eventMap.coffee, client/controllers/userEvents.coffee, client/views/mapFilters.jade, collections/incidents.coffee, collections/userEvents.coffee, imports/schemas/incidentReport.coffee
* Created lastIncidentDate to the event object.
* Order Event list and event map list by lastIncidentDate
=> Last incident date

client/controllers/curatorInbox.coffee, client/router.coffee, client/views/curatorInbox.jade, collections/articles.coffee, imports/stylesheets/curator.import.styl, imports/ui/inlineDateRangePicker.coffee
Story:
https://www.pivotaltracker.com/story/show/129926215
- Adds a calendar to the Curator Inbox
- Adds server-side filter for the subscription
- Makes many UI updates to the curator inbox to allow range filtering using multiple sectioned reactive-tables
=> Adds range filtering for the curator inbox

imports/stylesheets/_main.styl, imports/stylesheets/curator.import.styl, imports/stylesheets/loading.import.styl, imports/stylesheets/mapFilters.import.styl, imports/stylesheets/mixins.import.styl
Uses Nib which is included in the Meteor Stylus package.
Also removes browser specific properties that will now be added by Nib.
=> Import nib

client/controllers/curatorInbox.coffee, client/views/curatorInbox.jade, collections/articles.coffee, imports/stylesheets/curator.import.styl, server/interfaces.coffee
PR takes care of 2 related stories:
https://www.pivotaltracker.com/story/show/129926131
https://www.pivotaltracker.com/story/show/130742703
- Adds option to mark articles as reviewed.
- Adds additional “reviewed” filter for the curator inbox.
- Fixes minor bug with the tables on the inbox not displaying all articles.
There appears to be some odd behavior caused by us having multiple redundant/duplicate articles in the collection for our testing. For instance, accepting an article might shift it’s order on the list.
This should be remedied when implementing the story: https://www.pivotaltracker.com/story/show/129926009
=> Adds article acceptance and an additional filter

.meteor/packages, .meteor/versions
This PR just adds a meteor package which resides here: https://github.com/sturmer-eha/meteor-nojs-banner and here: https://atmospherejs.com/ecosturmer/nojs-banner
=> add the noJS-banner package

client/controllers/adminUser.coffee, client/router.coffee, client/views/admins.jade, collections/allUsers.coffee
https://www.pivotaltracker.com/story/show/131278095
- Alows admins to assign "curator" role to users.
- Lightly tweaks the adminUsers view for better role visibility.
=> Adds "curator" role in adminUser panel

client/controllers/curatorInbox.coffee, client/views/curatorInbox.jade, eidr-connect.yml, imports/stylesheets/curator.import.styl, methods/promedPosts.coffee, server/publications.coffee
* SPA_MONGO_URL added to docker compose file.
* Curator inbox uses promedDate.
* scrapeDate is no longer used.
* EIDR no longer stores post content.
* Full post titles are used.
* Filtering by date range is fixed.
=> Misc. curator inbox issues

client/controllers/eventMap.coffee, client/controllers/mapFilters.coffee, client/views/eventMap.jade, client/views/mapFilters.jade, imports/stylesheets/eventMap.import.styl, imports/ui/mapMarkers.coffee, server/publications.coffee
https://www.pivotaltracker.com/story/show/130518645
Steps: 
1. Click on the 'Event Map'
2. Click on a marker
3. Notice popup dialog contains information about the most severe incident
**Note: This PR also fixes a bug using the Event Map filter**
Steps:
1. Click on the 'Event Map'
2. Click on an event from the left side 'filter'
3. Click on a map marker
4. Notice popup now displays the location
=> adds feature to display incident information when map markers are shown

client/controllers/eventMap.coffee
https://www.pivotaltracker.com/story/show/130367327
=> reverses pagination so UI doesn't appear to start at the end

client/controllers/header.coffee
https://www.pivotaltracker.com/story/show/132239883
=> open dropdown menu mouseover/mouseout

client/controllers/incidentReports.coffee, client/controllers/sourceModal.coffee, server/interfaces.coffee
Details about the bug: https://www.pivotaltracker.com/story/show/130514787
This also fixes a bug in eliminating previously added articles from the article suggestions.
=> Fix publication date autofill bug

client/controllers/curatorEvents.coffee, client/views/curatorEvents.jade, client/views/curatorInbox.jade, imports/stylesheets/curator.import.styl, imports/stylesheets/globals.import.styl, imports/stylesheets/utils.import.styl, imports/stylesheets/variables.import.styl
Related stories:
https://www.pivotaltracker.com/story/show/132919107
https://www.pivotaltracker.com/story/show/132919017
=> Implement curator inbox event search and new event association UI

client/controllers/curatorInbox.coffee, client/views/curatorInbox.jade, imports/stylesheets/curator.import.styl, imports/stylesheets/globals.import.styl
Moves the review (formally _accept_) button and combine toggling into single button.
=> Move reviewed button and undo hover state

client/controllers/curatorInbox.coffee, client/views/curatorInbox.jade, imports/stylesheets/curator.import.styl, imports/stylesheets/index.styl, imports/stylesheets/lists.import.styl, methods/promedPosts.coffee
Adds the content copy for source and allows user to toggle its visibility.
~~**Let's merge in #125 before we merge this so I can update the position of the toggle button relative to the new reviewed button.**~~
=> Add source content and allow user to toggle visibility

client/controllers/incidentReports.coffee, imports/charts/Axes.coffee
This should resolve the issue of duplicate labels showing at certain zoom levels.
=> changing threshold at which we show H:M for x axis

client/controllers/curatorInbox.coffee
Fixes a bug where the first record in the inbox was being clicked multiple times
=> fixing multiple click bug

client/views/curatorEvents.jade, imports/stylesheets/curator.import.styl
PT Story: https://www.pivotaltracker.com/story/show/133132647
=> Add info button to events table in curator inbox details

client/controllers/curatorSuggestedEvents.coffee, client/views/curatorEvents.jade
Fixes the missing title prop for the curatorSuggestedEvents template by query against curatorSources using the new reactive var `selectedSourceId`
=> fix missing title property

client/controllers/curatorInbox.coffee, client/views/curatorInbox.jade
PT: https://www.pivotaltracker.com/story/show/133191391
Also fixes a bug with searching the source list: https://www.pivotaltracker.com/story/show/133359851
=> Do not show date header if there are no corresponding sources

client/controllers/curatorEvents.coffee, client/views/curatorEvents.jade, imports/stylesheets/curator.import.styl
Allows users to suggest incidents from the curator inbox
=> Suggest incidents 2

client/controllers/articles.coffee, client/controllers/curatorEvents.coffee, client/controllers/sourceModal.coffee, client/views/sourceModal.jade, imports/schemas/article.coffee, methods/articles.coffee, server/startup.coffee
If a title is available for the document we will now display it.  Will have a separate job that will update documents to include the title.
=> Adding title to doc when adding source.  

client/views/curatorInbox.jade, imports/stylesheets/curator.import.styl, imports/stylesheets/event.import.styl, imports/stylesheets/navTabs.import.styl, imports/stylesheets/variables.import.styl
This was a little independent of the chore I'm working on so I thought I'd open a PR specifically for it.
=> Update styles of headers and list items

client/views/curatorEvents.jade, imports/stylesheets/curator.import.styl
This shows an _add incident_ button (along with the info button) inline.
=> Make incident report addition more explicit

client/controllers/curatorInbox.coffee, client/views/curatorInbox.jade, imports/stylesheets/curator.import.styl, imports/stylesheets/forms.import.styl
I'm having trouble focusing the input after clicking the icon.
Maybe this animation isn't necessary?
PT Chore: https://www.pivotaltracker.com/story/show/133627883
=> Curator inbox header ui updates

client/controllers/curatorInbox.coffee, client/views/curatorInbox.jade, imports/stylesheets/curator.import.styl, imports/stylesheets/forms.import.styl, imports/stylesheets/tooltips.import.styl
- Sets tooltip color
- Adjusts placement
- removes tooltip after click
=> Update inbox tooltips - do not show after click

client/controllers/userEvent.coffee, client/views/articles.jade, client/views/incidentReports.jade, client/views/userEvent.jade, imports/stylesheets/event.import.styl
This may require some more work. I'm not sure the suggested articles logic is working since I'm calling the modal without delivering some data.
=> Show add report/source btns if none and content if exists

client/controllers/curatorEvents.coffee, client/controllers/editEventModal.coffee, client/controllers/userEvent.coffee, client/controllers/userEvents.coffee, client/views/curatorEvents.jade, client/views/editEventDetailsModal.jade, imports/stylesheets/buttons.import.styl, imports/stylesheets/curator.import.styl, methods/articles.coffee, methods/incidentReports.coffee, methods/userEvents.coffee
Allows users to add events in the curator inbox. When an event is added, its automatically associated with the selected source. It modifies the edit event modal — combines the adding and editing events.
PT Story: https://www.pivotaltracker.com/story/show/128147377
PT Bug: https://www.pivotaltracker.com/story/show/133516463
=> Curator inbox add new event

client/controllers/curatorInbox.coffee, client/views/articles.jade, client/views/curatorEvents.jade, client/views/events/locationList.jade, imports/stylesheets/curator.import.styl, imports/stylesheets/events/event.import.styl, imports/stylesheets/forms.import.styl
Also fixes the focus issue with the initially hidden search input in the curator inbox left pane header.
=> Make search inputs consistent

imports/stylesheets/events/sources.import.styl
Small layout tweak to the event source details area.
=> Fix styles of event source details links/dates

client/controllers/curatorInbox.coffee, client/views/curatorInbox.jade, client/views/footer.jade, client/views/splash.jade, imports/stylesheets/about.import.styl, imports/stylesheets/curator.import.styl, imports/stylesheets/eventMap.import.styl, imports/stylesheets/footer.import.styl, imports/stylesheets/mapFilters.import.styl, imports/stylesheets/ui.import.styl, imports/stylesheets/variables.import.styl
PT Chore: https://www.pivotaltracker.com/story/show/134377785
=> Make left and right padding consistent throughout

client/views/events/location.jade, client/views/events/summary.jade, client/views/incidentReports.jade, imports/stylesheets/events/incidentDetails.import.styl, imports/stylesheets/events/locations.import.styl, imports/stylesheets/events/metadata.import.styl
Fixes styles of details in the incident report and locations tables.
=> Style incident report details for small screens

client/controllers/curatorInbox.coffee, imports/stylesheets/curator.import.styl
PT bug: https://www.pivotaltracker.com/story/show/134718189
=> Hide overflow of header and show related tooltips on body

client/controllers/feeds.coffee, client/views/feeds.jade, client/views/header.jade, imports/stylesheets/feeds.import.styl, imports/stylesheets/lists.import.styl, imports/stylesheets/ui.import.styl, methods/feeds.coffee
PT story: https://www.pivotaltracker.com/story/show/134515971
=> Implement feed deletion

client/controllers/deleteConfirmation/deleteConfirmationModalBody.coffee, client/controllers/feeds.coffee, imports/ui/deletion.coffee, methods/feeds.coffee
Also adds confirmation and imports a function associated with deletion.
=> Fix feed removal

client/router.coffee, client/views/admins.jade, imports/stylesheets/index.styl, imports/stylesheets/userManagement.import.styl
Fix list of curators
[PT BUG](https://www.pivotaltracker.com/story/show/135354941)
=> Allow admins to grant curator role to self

client/router.coffee, client/views/layout/header.jade
Refactor `onBeforeAction` methods of most routes
=> Allow regular users to logout

.meteor/packages, .meteor/versions, start-test-server.sh
tmeasday:acceptance-test-driver: A simple "null" driver for acceptance
tests
See https://github.com/tmeasday/acceptance-test-driver
https://www.pivotaltracker.com/story/show/135644435
=> adds isAppTest conditional

client/views/incidentReports/incidentReports.jade, imports/stylesheets/events/event.import.styl, imports/stylesheets/globals.import.styl, imports/stylesheets/mixins.import.styl, imports/stylesheets/tables.import.styl, imports/stylesheets/variables.import.styl
[PT Chore](https://www.pivotaltracker.com/story/show/135778295)
One of the major updates is to the pagination UI on mobile devices ☎️ . Reduces to simple buttons like so:
=> Fix widths and postitioning of table elements

imports/stylesheets/curator.import.styl, imports/stylesheets/tables.import.styl
Fixes spacing and margin of curator inbox table pagination.
=> Fix minor spacing issue in curator inbox pagination

client/controllers/events/userEvent.coffee, client/controllers/events/userEvents.coffee, client/views/events/userEvent.jade, methods/userEvents.coffee, server/methods.coffee, server/publications.coffee, server/router.coffee
Marking userEvent records as deleted instead of actually deleting them.
=> adding soft delete logic

client/views/maps/markerPopup.jade, imports/stylesheets/maps/markerPopup.import.styl
Fixes width issue resulting in clipping of the circle SVG.
[PT Bug](https://www.pivotaltracker.com/story/show/136050737)
=> Give map tooltip content maximum width

client/postMessageHandler.coffee
See: https://github.com/ecohealthalliance/bsve-integration/pull/13
https://www.pivotaltracker.com/story/show/134698799
=> added feature to call BSVE.ui.alert upon authentication failure

.config/chimp.js, .meteor/packages, client/controllers/incidentReports/incidentForm.coffee, client/controllers/incidentReports/incidentModal.coffee, client/controllers/incidentReports/suggestedIndidentModal.coffee, client/views/incidentReports/incidentForm.jade, client/views/incidentReports/incidentModal.jade, client/views/incidentReports/suggestedIncidentModal.jade, imports/stylesheets/forms/checkButton.import.styl, imports/stylesheets/forms/forms.import.styl, imports/stylesheets/forms/index.import.styl, imports/stylesheets/index.styl, imports/stylesheets/pillSelector.import.styl, imports/utils.coffee, tests/features/step_definitions/incident_steps.coffee
This reworks how we receive information from the Incident Report form. I recently changed things up to use reactiveVars to track the values of certain properties (when switching the select inputs to button-based checkboxes) Those buttons are now styled radio and checkbox inputs which allow us to receive all submitted data through the form.
=> Customly styled form elements

client/controllers/sourceModal.coffee, client/views/incidentReports/incidentModal.jade, client/views/sourceModal.jade, imports/stylesheets/datepicker.import.styl, imports/stylesheets/forms/forms.import.styl, imports/stylesheets/incidents/incidentForm.import.styl, imports/stylesheets/loading.import.styl, imports/stylesheets/modals.import.styl, imports/stylesheets/sources.import.styl, imports/stylesheets/utils.import.styl, imports/stylesheets/variables.import.styl, methods/articles.coffee
One #188 is merged I'll probably update the checkbox for 'suggest incident reports'
=> Improve UX and style event source modal

client/controllers/incidentReports/suggestedIncidentsModal.coffee
Omit dates that are entirely in the future and truncate date ranges that extend into the future.
=> Limit suggested article dates to before publication date

client/controllers/curatorInbox/curatorEvents.coffee, client/controllers/curatorInbox/curatorInbox.coffee, client/controllers/curatorInbox/curatorSourceDetails.coffee, imports/stylesheets/curator.import.styl, methods/curatorSources.coffee
Adds a reactiveVar which tracks if an event has been added. I so and the user selects another source, the source is marked reviewed and the next, selected, source is shown.
[PT Story](https://www.pivotaltracker.com/story/show/134378559)
=> Mark a source reviewed when leaving if has assocaiated events

client/controllers/curatorInbox/curatorSourceDetails.coffee, client/views/curatorInbox/curatorInbox.jade
https://www.pivotaltracker.com/story/show/136382371
- use a helper to dynamically update the tooltip title
=> fix title in tooltip of selected source

.config/chimp.js, tests/features/sources.feature, tests/features/step_definitions/common_steps.coffee, tests/features/step_definitions/events_steps.coffee, tests/features/step_definitions/sources_steps.coffee
This starts test for sources.
I have a few questions:
- Should we assume a connection to the SPA server or the associated db? [Here](https://github.com/ecohealthalliance/eidr-connect/blob/a75626f1defbc263159af3d1be5d1cedf91f434d/tests/features/step_definitions/sources_steps.coffee#L40) I kind of stub out the date and time since it depends on said connection. Is this the path we should take?
- Should I go ahead and add tests for reviewing incident reports from the newly added source?
- Do we need the chimp logs?
=> Add tests for sources

client/controllers/sourceModal.coffee, imports/ui/inlineDateRangePicker.coffee
Fixes [this bug](https://www.pivotaltracker.com/story/show/136507507) and I figured out a better way of changing the day abbreviations.
=> Fix source date input selector and trimming month

client/controllers/events/createEventModal.coffee, client/controllers/events/editEventModal.coffee, client/views/createEventModal.jade, client/views/events/editEventDetailsModal.jade, imports/schemas/userEvent.coffee, imports/stylesheets/forms/forms.import.styl, methods/userEvents.coffee, server/router.coffee
By default none of the events will be displayed.
=> Add displayOnPromed event property

Dockerfile, server/router.coffee
This will eventually be used to sync automatic deploys on the BSVE environment
=> adding route to display contents of revision.txt file

client/controllers/incidentReports/incidentForm.coffee, client/controllers/incidentReports/suggestedIncidentsModal.coffee, client/controllers/incidentReports/suggestedIndidentModal.coffee, client/controllers/locationSelect2.coffee, client/views/incidentReports/incidentForm.jade, client/views/incidentReports/suggestedIncidentModal.jade, imports/stylesheets/forms/index.import.styl, imports/stylesheets/forms/suggested.import.styl, imports/stylesheets/incidents/incidentForm.import.styl, imports/stylesheets/modals/modals.import.styl
This also fixes the status field bug here:
https://www.pivotaltracker.com/story/show/136737257
=> Add visual indication when fields are auto-filled

client/controllers/searchInput.coffee
https://www.pivotaltracker.com/story/show/137029065
=> fix: search filter does not reset

methods/promedPosts.coffee
Adds filter and field for 'feedId' to fetchPromedPosts so that only main ProMED feed posts appear in the inbox.
https://www.pivotaltracker.com/story/show/136512391
=> add feedId to fetchPromedPosts

client/controllers/events/userEvents.coffee, client/controllers/searchInput.coffee
https://www.pivotaltracker.com/story/show/137046527
=> fix: hide loading indicator when results <= 1

client/views/articles.jade, imports/stylesheets/events/metadata.import.styl, imports/stylesheets/events/sources.import.styl, imports/stylesheets/modals/modals.import.styl
Fixes some layout issues on medium and small screens.
=> Update event source detail UI on small screens

client/controllers/sourceModal.coffee, client/views/incidentReports/incidentForm.jade, client/views/incidentReports/incidentModal.jade, client/views/sourceModal.jade, imports/stylesheets/buttons.import.styl, imports/stylesheets/datepicker.import.styl, imports/stylesheets/forms/checkButton.import.styl, imports/stylesheets/incidents/incidentForm.import.styl, imports/stylesheets/modals/modals.import.styl, imports/stylesheets/pillSelector.import.styl, tests/features/step_definitions/sources_steps.coffee
Update suggest incident reports checkbox
[PT Chore](https://www.pivotaltracker.com/story/show/137054223)
=> Fix small screen layout of add incident report modal

imports/stylesheets/buttons.import.styl, imports/stylesheets/curator.import.styl, imports/stylesheets/datepicker.import.styl, imports/stylesheets/events/event.import.styl, imports/stylesheets/footer.import.styl, imports/stylesheets/forms/forms.import.styl, imports/stylesheets/globals.import.styl, imports/stylesheets/header.import.styl, imports/stylesheets/maps/eventMap.import.styl, imports/stylesheets/modals/modals.import.styl, imports/stylesheets/utils.import.styl, imports/stylesheets/variables.import.styl
Meets [these accessibility standards](https://www.w3.org/WAI/WCAG20/quickref/?currentsidebar=%23col_overview&showtechniques=143#visual-audio-contrast-contrast).
[PT Chore](https://www.pivotaltracker.com/story/show/137298983)
=> Ensure text contrast ratios meet at least AA standards

client/views/admins.jade, client/views/articles.jade, client/views/cancelConfirmation/cancelConfirmationModalBody.jade, client/views/contactUs.jade, client/views/curatorInbox/curatorEvents.jade, client/views/curatorInbox/curatorInbox.jade, client/views/curatorInbox/curatorSourceDetails.jade, client/views/curatorInbox/curatorSuggestedEvents.jade, client/views/deleteConfirmation/deleteConfirmationModalBody.jade, client/views/download.jade, client/views/events/location.jade, client/views/events/summary.jade, client/views/events/userEvents.jade, client/views/feeds.jade, client/views/incidentReports/addIncidentReport.jade, client/views/incidentReports/detailIcon.jade, client/views/incidentReports/incidentForm.jade, client/views/incidentReports/incidentReport.jade, client/views/incidentReports/incidentReports.jade, client/views/incidentReports/inlineDateRangePicker.jade, client/views/layout/footer.jade, client/views/layout/header.jade, client/views/splash.jade
Hide icons from screen readers as necessary
[PT Chore](https://www.pivotaltracker.com/story/show/137299525)
https://www.w3.org/WAI/WCAG20/quickref/#navigation-mechanisms-refs
=> Ensure button/link purpose is indicated

imports/stylesheets/header.import.styl
[PT BUG](https://www.pivotaltracker.com/story/show/137365685)
=> Fix header nav hieght, spacing and hover issues

client/router.coffee, client/startup.coffee
[PT CHORE](https://www.pivotaltracker.com/story/show/137299319)
=> Add lang to html tag and ensure pages are contextually named

client/controllers/createAccount.coffee, client/controllers/locationSelect2.coffee, client/views/articles.jade, client/views/createAccount.jade, client/views/createEventModal.jade, client/views/events/editEventDetailsModal.jade, client/views/incidentReports/incidentForm.jade, client/views/sourceModal.jade, imports/stylesheets/validator.import.styl
https://www.w3.org/WAI/WCAG20/quickref/#minimize-error-identified
[PT Chore](https://www.pivotaltracker.com/story/show/137299137)
=> Ensure invalid inputs are accompanied by error message

tests/features/incident.feature, tests/features/step_definitions/incident_steps.coffee
https://www.pivotaltracker.com/story/show/136957537
https://www.pivotaltracker.com/story/show/136959379
=> adds tests to abandon/confirm suggested source and IR

client/views/admins.jade, client/views/articles.jade, client/views/incidentReports/addIncidentReport.jade, client/views/incidentReports/incidentReport.jade, imports/stylesheets/events/sources.import.styl
[PT Bug](https://www.pivotaltracker.com/story/show/137362759)
=> Restrict editing/deleting of sources and IRs to admins

client/controllers/incidentReports/incidentForm.coffee
[PT Story](https://www.pivotaltracker.com/story/show/137420161)
=> Allow users to deselect incident status

client/controllers/curatorInbox/curatorInbox.coffee
https://www.pivotaltracker.com/story/show/137299227
=> append template instance data.index to create unique ID

client/controllers/curatorInbox/curatorInbox.coffee, client/views/curatorInbox/curatorInbox.jade, imports/stylesheets/curator.import.styl
Steps: 
1. Login as authenticated user
2. Navigate to /curator-inbox by clicking [Inbox] button
3. Expand/Collapse dates within the inbox
Note: Button [Back to Top] fades In/Out based on the scrollTop
4. Click the button [Back to Top]
Note: The div is scrolled back to the top
https://www.pivotaltracker.com/story/show/137298815
=> adding feature back-to-top

client/controllers/incidentReports/incidentForm.coffee, imports/utils.coffee
Fixes this bug: https://www.pivotaltracker.com/story/show/137420455
=> Make suggested incident report dates use article timezone

imports/stylesheets/curator.import.styl, imports/stylesheets/events/event.import.styl, imports/stylesheets/events/incidentDetails.import.styl, imports/stylesheets/forms/checkButton.import.styl, imports/stylesheets/forms/forms.import.styl, imports/stylesheets/forms/suggested.import.styl, imports/stylesheets/maps/mapFilters.import.styl, imports/stylesheets/modals/modals.import.styl, imports/stylesheets/pillSelector.import.styl, imports/stylesheets/searchInput.import.styl, imports/stylesheets/select2.import.styl, imports/stylesheets/tables.import.styl, imports/stylesheets/utils.import.styl
[PT Chore](https://www.pivotaltracker.com/story/show/137543433)
=> Add comment to FontAwesome unicodes indicating class - meaning

client/controllers/sourceModal.coffee, client/views/sourceModal.jade, imports/stylesheets/datepicker.import.styl, server/methods.coffee, tests/features/incident.feature
This autofills the source title when source URLs are manually entered.
I branched off of #257 because it contains a few pertinent fixes.
It was registered as a [bug](https://www.pivotaltracker.com/story/show/137420353) but I'm not sure we implemented this in the past.
=> Source title autofill

imports/stylesheets/forms/suggested.import.styl
Fixes bug where content overflows container.
[PT Bug](https://www.pivotaltracker.com/story/show/137903563)
=> Add max-width to incident form panes

client/controllers/incidentReports/incidentForm.coffee, client/views/incidentReports/incidentForm.jade, client/views/incidentReports/suggestedIncidentModal.jade, imports/utils.coffee
[PT Story](https://www.pivotaltracker.com/story/show/137783437)
=> Do not show source URL in IR review/confirmation

imports/stylesheets/events/event.import.styl, imports/stylesheets/tables.import.styl
Related to [this chore](https://www.pivotaltracker.com/story/show/137898181).
=> Do not truncate table cell content and vertically center action

client/controllers/header.coffee
https://www.pivotaltracker.com/story/show/137132095
=> fix: clicking dropdown at mobile causes parent to close

imports/stylesheets/tooltips.import.styl
Fixes [this bug](https://www.pivotaltracker.com/story/show/137790399)
=> Remove tooltip arrow positioning on small screen

client/controllers/incidentReports/incidentReports.coffee, imports/charts/Axes.coffee
https://www.pivotaltracker.com/story/show/138618367
=> fix hidden chart labels; update yLabel text

client/postMessageHandler.coffee
https://www.pivotaltracker.com/story/show/138334481
=> Enable BSVE data exchange for EIDR-C incident report extractor

client/controllers/articles.coffee, client/controllers/events/editEventModal.coffee, client/controllers/incidentReports/incidentForm.coffee, client/controllers/incidentReports/incidentModal.coffee, client/controllers/incidentReports/suggestedIncidentsModal.coffee, client/controllers/incidentReports/suggestedIndidentModal.coffee, client/controllers/loading.coffee, client/controllers/notification.coffee, client/controllers/sourceModal.coffee, client/views/incidentReports/incidentForm.jade, client/views/incidentReports/incidentModal.jade, client/views/incidentReports/suggestedIncidentModal.jade, client/views/incidentReports/suggestedIncidentsModal.jade, client/views/loading.jade, client/views/notification.jade, client/views/sourceModal.jade, imports/stylesheets/forms/suggested.import.styl, imports/stylesheets/incidents/incidents.import.styl, imports/stylesheets/index.styl, imports/stylesheets/loading.import.styl, imports/stylesheets/modals/modals.import.styl, imports/stylesheets/notification.import.styl, imports/ui/modals.coffee, imports/ui/notification.coffee, tests/features/incident.feature, tests/features/step_definitions/common_steps.coffee, tests/features/step_definitions/incident_steps.coffee, tests/features/step_definitions/sources_steps.coffee
Establishes an improved UX for source addition and IR review. Animates modals off and on stage and adds notifications informing the user the results of their actions.
Also:
- Makes the snippet equal (and scrollable) to the height of the form if it is greater.
- Updates to position of the loading indicator in the suggested sources list
- fixes [this bug](https://www.pivotaltracker.com/story/show/138184901)
=> Improve UX of source addition and IR review

client/controllers/deleteConfirmation/deleteConfirmationModalBody.coffee, client/controllers/events/createEventModal.coffee, client/controllers/smartEvents/editSmartEventDetailsModal.coffee, client/controllers/smartEvents/smartEvent.coffee, client/controllers/smartEvents/smartEventSummary.coffee, client/router.coffee, client/views/smartEvents/editSmartEventDetailsModal.jade, client/views/smartEvents/smartEvent.jade, client/views/smartEvents/smartEventSummary.jade, client/views/smartEvents/smartEvents.jade, imports/collections/smartEvents.coffee, imports/schemas/smartEvent.coffee, imports/ui/modals.coffee, methods/smartEvents.coffee, server/publications.coffee
https://www.pivotaltracker.com/story/show/139701083
This adds basic pages, methods, publications, and a collection and schema for smart events. Most of the code is adapted from the user events code.
@jgoley Could you review this?
=> Groundwork for Smart Events

client/controllers/curatorInbox/curatorInbox.coffee, client/controllers/events/userEvents.coffee, client/controllers/smartEvents/smartEvents.coffee, client/startup.coffee, client/views/events/userEvents.jade, client/views/smartEvents/smartEvents.jade, imports/reactiveTable.coffee, imports/stylesheets/forms/checkButton.import.styl, imports/stylesheets/modals/modals.import.styl, imports/stylesheets/ui.import.styl, server/publications.coffee
This branches of the yet-to-be-merged scaffolding branch (#286) . Sets of the table and related filtering mentioned in [this PT story](https://www.pivotaltracker.com/story/show/139700905).
=> Smart events table

client/controllers/smartEvents/smartEvents.coffee
Noticed the _show my events_ button was requiring two clicks to change state when I pulled in the latest master. My bad.
=> Toggle state of "show my events" button

client/controllers/incidentReports/incidentReports.coffee, client/controllers/reactiveTable.coffee, client/controllers/smartEvents/editSmartEventDetailsModal.coffee, client/controllers/smartEvents/smartEvent.coffee, client/router.coffee, client/views/articles.jade, client/views/events/userEvent.jade, client/views/incidentReports/incidentReports.jade, client/views/smartEvents/editSmartEventDetailsModal.jade, client/views/smartEvents/smartEvent.jade, client/views/smartEvents/smartEventSummary.jade, imports/schemas/smartEvent.coffee, methods/smartEvents.coffee, server/methods.coffee, server/publications.coffee, server/startup.coffee
[PT Story](https://www.pivotaltracker.com/story/show/139701435)
=> Add disease property to smart events and get via form

client/controllers/curatorInbox/curatorSourceDetails.coffee, client/views/curatorInbox/curatorSourceDetails.jade
Basically just removing conditional and toggle logic for the source text section
=> showing source text by default

imports/stylesheets/curatorInbox.import.styl
[PT Bug](https://www.pivotaltracker.com/story/show/141351653)
=> Fix curator inbox souce title spacing

client/controllers/curatorInbox/curatorInbox.coffee
Small update to fix a bug associated with the recent change to curator inbox.
[PT Bug](https://www.pivotaltracker.com/story/show/141355003)
=> Do not update selected source if currently selected

client/controllers/articles.coffee, client/controllers/incidentReports/incidentForm.coffee, client/controllers/incidentReports/incidentReport.coffee, client/controllers/incidentReports/incidentReports.coffee, client/views/incidentReports/incidentForm.jade, imports/ui/helpers.coffee
[PT Bug](https://www.pivotaltracker.com/story/show/141422971)
=> Show source url as text in IR form if source exists

client/controllers/curatorInbox/curatorSourceDetails.coffee, client/controllers/curatorInbox/sourceIncidentReports.coffee, client/controllers/incidentReports/incidentTable.coffee, client/views/curatorInbox/curatorSourceDetails.jade, client/views/curatorInbox/sourceIncidentReports.jade, client/views/incidentReports/incidentTable.jade, imports/stylesheets/curatorInbox.import.styl, imports/stylesheets/events/event.import.styl, imports/stylesheets/incidents/incidents.import.styl, imports/stylesheets/maps/eventMap.import.styl
[PT story](https://www.pivotaltracker.com/story/show/141167197) to show a table of rejected IRs.
=> Curator inbox rejected ir table

client/controllers/curatorInbox/curatorSourceDetails.coffee, client/controllers/incidentReports/incidentForm.coffee, client/controllers/incidentReports/incidentModal.coffee, client/controllers/incidentReports/incidentTable.coffee, client/views/incidentReports/incidentForm.jade
[PT Story](https://www.pivotaltracker.com/story/show/141776231)
=> Open edit IR modal when user clicks source text annotation

client/controllers/curatorInbox/curatorSourceDetails.coffee, client/controllers/curatorInbox/sourceIncidentReports.coffee, client/controllers/incidentReports/incidentModal.coffee, client/controllers/incidentReports/incidentTable.coffee, client/views/curatorInbox/curatorSourceDetails.jade, client/views/curatorInbox/sourceIncidentReports.jade, imports/stylesheets/curatorInbox.import.styl, methods/incidentReports.coffee
Builds on #306 to accomplish this [PT Story](https://www.pivotaltracker.com/story/show/141165563) to allow curators to add new events to source.
=> Curator inbox add ir

client/controllers/incidentReports/incidentTable.coffee, client/views/incidentReports/incidentTable.jade, imports/stylesheets/incidents/incidentTable.import.styl, imports/stylesheets/incidents/incidents.import.styl, imports/stylesheets/incidents/index.import.styl, imports/stylesheets/index.styl
[PT Story](https://www.pivotaltracker.com/story/show/142640157)
Not really happy with the UX of editing but this is a temporary solution.
=> Curator inbox click ir row to select

client/controllers/events/locationList.coffee, client/controllers/geolocations.coffee, client/controllers/locationSelect2.coffee, client/controllers/maps/markerPopup.coffee, client/controllers/smartEvents/smartEventSummary.coffee, client/router.coffee, imports/formatLocation.coffee, imports/ui/helpers.coffee
[PT Bug](https://www.pivotaltracker.com/story/show/142947695)
=> Fix IR details - use import instead of require

client/controllers/curatorInbox/curatorSourceDetails.coffee, client/controllers/curatorInbox/sourceIncidentReports.coffee, client/controllers/incidentReports/annotatedContent.coffee, client/controllers/incidentReports/incidentTable.coffee, client/views/curatorInbox/curatorSourceDetails.jade, client/views/curatorInbox/sourceIncidentReports.jade, client/views/incidentReports/incidentTable.jade, imports/stylesheets/annotatedContent.import.styl, imports/stylesheets/curatorInbox.import.styl, imports/stylesheets/incidents/incidentTable.import.styl, imports/ui/annotation.coffee
[PT Story](https://www.pivotaltracker.com/story/show/142863589)
There's one UX-related issue that may not be resolvable—we can't change the cursor when the mouse is over the annotations. It's not a huge deal but it would be nice to have some sort of indication, especially since we plan to add additional features post-click.
=> Curator inbox click annotation to scroll

client/controllers/incidentReports/incidentReports.coffee, imports/charts/Axes.coffee, imports/charts/Plot.coffee, imports/charts/Zoom.coffee
Makes it so you can't zoom below 0 and no longer displays decimals (whole numbers only)
=> Scatter bounds

client/views/events/summary.jade
[PT Bug](https://www.pivotaltracker.com/story/show/142142847)
=> Display correct icon for editing event metadata

client/views/events/locationList.jade, imports/stylesheets/events/event.import.styl
I imagine this UI will change in the future so I made a small change to how the message is presented.
=> Fix no locations message

client/controllers/incidentReports/incidentTable.coffee, client/controllers/incidentReports/suggestedIncidentModal.coffee, client/controllers/incidentReports/suggestedIncidentsModal.coffee, client/views/incidentReports/suggestedIncidentModal.jade
[PT Story](https://www.pivotaltracker.com/story/show/142863553)
=> Curator inbox show suggested ir modal when editing

client/controllers/incidentReports/incidentReports.coffee, client/views/incidentReports/incidentTable.jade, imports/ui/helpers.coffee
[PT Story](https://www.pivotaltracker.com/story/show/142809815)
=> Format dates within curator inbox incident tables

client/controllers/incidentReports/incidentTable.coffee, client/controllers/incidentReports/suggestedIncidentModal.coffee, client/views/incidentReports/suggestedIncidentModal.jade
[PT Bug](https://www.pivotaltracker.com/story/show/143263801)
=> Remove IR from selected collection when accepted

client/controllers/curatorInbox/curatorSourceDetails.coffee, client/views/curatorInbox/curatorSourceDetails.jade, imports/stylesheets/curatorInbox.import.styl
[PT Bug](https://www.pivotaltracker.com/story/show/143260491)
=> Fix the marked reviewed animation and related UI bugs

client/controllers/curatorInbox/curatorSourceDetails.coffee
[PT Bug](https://www.pivotaltracker.com/story/show/143278763)
=> Clear selected source id when going back to doc list

imports/ui/annotation.coffee
[PT Bug](https://www.pivotaltracker.com/story/show/143314809)
=> Fix annotation colors in suggested incident modal

client/controllers/incidentReports/annotatedContent.coffee, client/controllers/incidentReports/newIncidentFromSelection.coffee, client/views/incidentReports/newIncidentFromSelection.jade, imports/stylesheets/annotatedContent.import.styl
This also reduces the vertical movement of the text due to the addition of the button at the top of the text container.
[PT Bug](https://www.pivotaltracker.com/story/show/143328867)
=> Prevent add IR btn from switching locations immediately

client/controllers/incidentReports/incidentTable.coffee, client/views/incidentReports/incidentTable.jade, imports/stylesheets/curatorInbox.import.styl, imports/stylesheets/incidents/incidentTable.import.styl, imports/stylesheets/tooltips.import.styl, imports/stylesheets/variables.import.styl, imports/ui/helpers.coffee
[PT Bug](https://www.pivotaltracker.com/story/show/143417569)
=> Fix width issues with IR table columns

client/controllers/incidentReports/incidentReports.coffee, client/views/incidentReports/incidentReports.jade, imports/charts/Plot.coffee, imports/charts/ScatterPlot.coffee
[PT Bug](https://www.pivotaltracker.com/story/show/143333009)
=> Only show plot zoome reset btn when plot zoomed

client/controllers/incidentReports/annotatedContent.coffee
[PT Bug](https://www.pivotaltracker.com/story/show/143498883)
=> Prevent users from adding incident from selection with no chars

client/controllers/events/createEventModal.coffee, client/views/events/createEventModal.jade
was causing problems when clicking the cancel button
=> disabling validation on blur

imports/stylesheets/events/event.import.styl
[PT Bug](https://www.pivotaltracker.com/story/show/143874471)
=> Fix visual bug with vertical spacing in event summary

methods/promedPosts.coffee, server/autoprocess.coffee, server/methods.coffee
This automatically submits the most recently added articles to the grits api. It also fixes a bug that prevented uncached historical date ranges from being queried.
=> Add autoprocessing

client/controllers/sourceModal.coffee, imports/schemas/article.coffee, methods/articles.coffee, server/autoprocess.coffee, server/indexes.coffee, server/methods.coffee
This adds schema validation for article/documents. It also fixes a bug where unresolved geoname ids would trigger exceptions instead of being ignored, and it might help with memory leak we saw on the server by using setInterval instead of recursive setTimeout calls.
=> Validate documents on submission

client/controllers/events/eventsTable.coffee, imports/reactiveTable.coffee
[PT Story](https://www.pivotaltracker.com/story/show/144099257)
Required a little finagling with the way we are managing sorting.
=> Sort events by lastModifiedDate

client/controllers/curatorInbox/curatorInbox.coffee, client/controllers/curatorInbox/curatorInboxSection.coffee, client/views/curatorInbox/curatorInbox.jade
[Fixes this bug](https://www.pivotaltracker.com/story/show/144609153)
Also fixes another bug where the first user added document was not being selected.
=> Fix first document not selected

client/controllers/curatorInbox/curatorInbox.coffee, client/controllers/curatorInbox/curatorInboxSection.coffee, client/controllers/sourceModal.coffee, methods/articles.coffee, server/methods.coffee, tests/features/curator_inbox.feature, tests/features/step_definitions/curator_inbox_steps.coffee
Fixes [this bug](https://www.pivotaltracker.com/story/show/145059173) and creates a Curator Inbox testing feature which tests document addition and and replaces tests for processing.
For some strange reason the tests fail in Chrome but pass in PhantomJS. I suppose the browser crashes or the user is logged out somehow during the waitForExist methods [here](https://github.com/ecohealthalliance/eidr-connect/blob/83b4b95de5a5c671b20e372c151b8402b718e34f/tests/features/step_definitions/curator_inbox_steps.coffee#L46-L50).
=> Tests incident suggestion

client/controllers/curatorInbox/addToEvent.coffee, client/controllers/curatorInbox/curatorSourceDetails.coffee, client/controllers/events/createEventModal.coffee, client/controllers/incidentReports/incidentForm.coffee, client/controllers/incidentReports/incidentModal.coffee, client/controllers/incidentReports/incidentReport.coffee, client/controllers/incidentReports/suggestedIncidentsModal.coffee, client/views/incidentReports/incidentForm.jade, client/views/incidentReports/incidentModal.jade, client/views/incidentReports/incidentTable.jade, imports/ui/snippets.coffee, methods/userEvents.coffee
Fixes [this bug](https://www.pivotaltracker.com/story/show/145689715)
Also changes how we pass in articles to the incident modal/form. Before, if the incident existed, we passed in an array of articles. I've changed this to passing in an incident object with an articleId (if creating a new incident) and checking for its existence.
=> Fix Create Event and Incident modal issues

client/controllers/curatorInbox/curatorSourceDetails.coffee, client/controllers/curatorInbox/sourceIncidentReports.coffee, client/controllers/events/editEventDetailsModal.coffee, client/controllers/incidentReports/annotatedContent.coffee, client/controllers/incidentReports/annotationOptions.coffee, client/controllers/incidentReports/incidentTable.coffee, client/controllers/incidentReports/newIncidentFromSelection.coffee, client/controllers/incidentReports/popup.coffee, client/controllers/incidentReports/suggestedIncidentModal.coffee, client/views/curatorInbox/curatorSourceDetails.jade, client/views/curatorInbox/sourceIncidentReports.jade, client/views/events/editEventDetailsModal.jade, client/views/incidentReports/annotationOptions.jade, client/views/incidentReports/newIncidentFromSelection.jade, client/views/incidentReports/popup.jade, client/views/maps/markerPopup.jade, imports/stylesheets/annotatedContent.import.styl, imports/stylesheets/buttons.import.styl, imports/stylesheets/index.styl, imports/stylesheets/maps/markerPopup.import.styl, imports/stylesheets/popup.import.styl, imports/ui/deletion.coffee, methods/userEvents.coffee, server/publications.coffee, tests/features/events.feature
[PT Story](https://www.pivotaltracker.com/story/show/145857845)
I intended to write tests but am currently having trouble running them locally.I encountered an issue with `fibers` which I've seen before but forgot how to resolve. 
```/Users/Goley/code/eidr-connect/node_modules/chimp/node_modules/cucumber/node_modules/fibers/bin/darwin-x64-47/fibers.node` is missing.```
I'll try to fix in the morning or if this is okay we could break tests out into a separate chore.
=> Click incident in doc to reveal actions

client/views/events/curatedEvent.jade
[PT Bug](https://www.pivotaltracker.com/story/show/146385483)
=> Only show resolved incidents plot if event has incidents

client/controllers/curatorInbox/curatorSourceDetails.coffee, client/controllers/curatorInbox/sourceIncidentReportsHeader.coffee, client/controllers/incidentReports/incidentTable.coffee, client/views/curatorInbox/curatorSourceDetails.jade, client/views/curatorInbox/sourceIncidentReportsHeader.jade, client/views/incidentReports/incidentTable.jade, imports/stylesheets/curatorInbox/headers.import.styl, imports/stylesheets/curatorInbox/table.import.styl, methods/incidentReports.coffee
This was a little more complex because I created separate template for the logic and such.
I branched from #370 to take advantage of some  overlapping changes it introduces.
[PT Story](https://www.pivotaltracker.com/story/show/146163505)
=> Ui enhancement fixed incident table header

client/controllers/articles.coffee, client/controllers/searchInput.coffee, client/views/curatorInbox/curatorInbox.jade, client/views/incidentReports/incidentReports.jade, imports/stylesheets/curatorInbox/curatorInbox.import.styl, imports/stylesheets/events/event.import.styl, imports/stylesheets/searchInput.import.styl
[PT Story](https://www.pivotaltracker.com/story/show/144115899)
I couldn't replicate the bug mentioned in the story. It may be an IE thing? @toph-allen Do you still have windows setup on your computer? If so, could you try to replicate this?
=> Fix inbox search box position

client/controllers/incidentReports/suggestedIncidentModal.coffee, client/views/incidentReports/incidentForm.jade, client/views/incidentReports/suggestedIncidentModal.jade, client/views/incidentReports/suggestedIncidentsModal.jade, imports/stylesheets/colorLegend.import.styl, imports/stylesheets/forms/forms.import.styl, imports/stylesheets/forms/suggested.import.styl, imports/stylesheets/incidents/incidentForm.import.styl, imports/stylesheets/incidents/incidents.import.styl, imports/stylesheets/mixins.import.styl, imports/stylesheets/modals/modals.import.styl, imports/stylesheets/navTabs.import.styl, imports/stylesheets/submitSource.import.styl
[PT Story](https://www.pivotaltracker.com/story/show/145932699)
Also: Update and fix styles of suggested incident modal
=> Allways show footer buttons in suggested incident modal

imports/stylesheets/forms/suggested.import.styl, imports/stylesheets/incidents/incidentForm.import.styl
Fixes some visual bugs I discovered after the updates to suggestedIncidentModal.
=> Fix widths, margins and padding of suggestedIncidentModal

client/controllers/incidentReports/newIncidentFromSelection.coffee, client/controllers/incidentReports/suggestedIncidentModal.coffee, client/controllers/incidentReports/suggestedIncidentsModal.coffee, client/controllers/sourceModal.coffee, server/methods.coffee
[PT Bug](https://www.pivotaltracker.com/story/show/146605755)
- Refactor `newIncidentFromSelection` controller logic
- Use simpleSchema `clean` method to filter out props not in schema
=> Fix adding manual annotation - keep annotation on save

client/controllers/events/summary.coffee, client/views/events/summary.jade, imports/stylesheets/events/metadata.import.styl, server/publications.coffee
[PT Bug](https://www.pivotaltracker.com/story/show/146685115)
=> Fix event page bugs 146685115

server/updaters.coffee
[PT Bug](https://www.pivotaltracker.com/story/show/146120925)
=> Remove userEventId from article documents

client/controllers/smartEvents/editSmartEventDetailsModal.coffee, client/views/smartEvents/smartEventSummary.jade
[PT Bug](https://www.pivotaltracker.com/story/show/144129177)
=> Open dateRangePicker when editing smart event dateRange

client/controllers/resolvedIncidentsPlot.coffee, client/views/resolvedIncidentsPlot.jade, imports/stylesheets/events/event.import.styl, imports/stylesheets/navTabs.import.styl
Pivotal Story: https://www.pivotaltracker.com/story/show/146605873
=> Add cumulative mode to resolved incident plot

client/controllers/downloadCSVModal.coffee, client/controllers/incidentReports/incidentReports.coffee, client/views/downloadCSVModal.jade, client/views/incidentReports/incidentReports.jade
[PT Bug](https://www.pivotaltracker.com/story/show/144726317)
=> Add loading spinner to CSV download button

client/controllers/curatorInbox/curatorSourceDetails.coffee, client/views/curatorInbox/curatorSourceDetails.jade, imports/stylesheets/curatorInbox/headers.import.styl, imports/stylesheets/events/sources.import.styl, imports/stylesheets/variables.import.styl, methods/articles.coffee
Pivotal story: https://www.pivotaltracker.com/story/show/143426399
=> Let users delete documents they added

client/controllers/curatorInbox/curatorSourceDetails.coffee, client/views/curatorInbox/curatorSourceDetails.jade, client/views/curatorInbox/sourceIncidentReportsHeader.jade, imports/stylesheets/annotatedContent.import.styl, imports/stylesheets/curatorInbox/curatorInbox.import.styl, imports/stylesheets/curatorInbox/headers.import.styl, imports/stylesheets/incidents/incidentList.import.styl, imports/stylesheets/incidents/incidents.import.styl, methods/articles.coffee
Story: https://www.pivotaltracker.com/story/show/144178479
=> Add document associated event indicators to inbox

client/views/curatorInbox/curatorSourceDetails.jade, imports/stylesheets/curatorInbox/curatorInbox.import.styl, imports/stylesheets/curatorInbox/headers.import.styl
Adds a delete button within the little error notification and moves the button up to the top header.
=> Fix deleting empty documents

imports/stylesheets/forms/suggested.import.styl
[PT Bug](https://www.pivotaltracker.com/story/show/148625217)
=> Apply will-change only to incident form in suggestedIncidentModal

imports/stylesheets/forms/forms.import.styl, imports/stylesheets/forms/parsley.import.styl, imports/stylesheets/forms/suggested.import.styl
[PT Bug](https://www.pivotaltracker.com/story/show/148483257)
=> Fix padding of suggested and parsley-error form elements

client/controllers/curatorInbox/curatorSourceDetails.coffee, client/controllers/curatorInbox/sourceIncidentReportsHeader.coffee, client/controllers/incidentReports/incidentForm.coffee, client/views/incidentReports/incidentForm.jade
[PT Bug](https://www.pivotaltracker.com/story/show/148583391)
=> Fix add new incident button

client/views/sourceModal.jade, imports/stylesheets/forms/forms.import.styl, imports/stylesheets/sources.import.styl, tests/features/step_definitions/curator_inbox_steps.coffee
[PT Story](https://www.pivotaltracker.com/story/show/148593417)
=> Always show buttons in add document modal

client/controllers/resolvedIncidentsPlot.coffee, imports/incidentResolution/incidentResolution.coffee, imports/incidentResolution/resolver.test.coffee
This bug lead to infinite rates that could break the EpiCurve plot like on this event: https://eidr-connect.eha.io/events/curated-events/gfnPs88SBb3aaBeeA
=> Fix matching start dates creating zero length subintervals

client/controllers/incidentReports/incidentModal.coffee, client/views/incidentReports/incidentModal.jade
Pivotal story: https://www.pivotaltracker.com/story/show/148468445
=> Remove save and duplicate event modal button

client/controllers/incidentReports/suggestedIncidentsModal.coffee, client/helpers.coffee, client/views/incidentReports/suggestedIncidentsModal.jade
[PT Bug](https://www.pivotaltracker.com/story/show/148748231)
=> Fix incident to text with 0 count in map and extracted incidents

client/controllers/events/curatedEvent.coffee, client/controllers/events/eventFiltration.coffee, client/controllers/events/eventIncidentReports.coffee, client/controllers/events/eventResolvedIncidents.coffee, client/views/events/curatedEvent.jade, client/views/events/eventFiltration.jade, client/views/events/eventIncidentReports.jade, client/views/events/eventNav.jade, client/views/events/eventResolvedIncidents.jade, client/views/incidentReports/extractIncidents.jade, client/views/incidentReports/incidentSecondaryDetails.jade, client/views/layout/extractIncidentsLayout.jade, client/views/layout/header.jade, imports/stylesheets/events/event.import.styl, imports/stylesheets/events/eventContent.import.styl, imports/stylesheets/events/eventFiltration.import.styl, imports/stylesheets/events/eventNav.import.styl, imports/stylesheets/events/events.import.styl, imports/stylesheets/events/resolvedIncidents.import.styl, imports/stylesheets/extractIncidents.import.styl, imports/stylesheets/footer.import.styl, imports/stylesheets/globals.import.styl, imports/stylesheets/header.import.styl, imports/stylesheets/incidents/incidentList.import.styl, imports/stylesheets/index.styl, imports/stylesheets/navTabs.import.styl, imports/stylesheets/variables.import.styl, tests/features/incidents.feature, tests/features/step_definitions/incidents_steps.coffee
Adds filter sidebar and filtration functionality for incident type, status and "other properties" (only travel related at this point). 
I'm not sure how I feel about having all the selectors unchecked by default. I might do a little research to determine if this is the best approach.
[PT Story](https://www.pivotaltracker.com/story/show/148836369)
=> Event page filtration

client/controllers/events/curatedEvent.coffee, client/controllers/events/eventFiltration.coffee, client/controllers/events/eventIncidentReports.coffee, client/controllers/events/eventResolvedIncidents.coffee, client/views/events/curatedEvent.jade, client/views/events/eventFiltration.jade, client/views/events/eventIncidentReports.jade, client/views/events/eventNav.jade, client/views/events/eventResolvedIncidents.jade, client/views/incidentReports/extractIncidents.jade, client/views/incidentReports/incidentSecondaryDetails.jade, client/views/layout/extractIncidentsLayout.jade, client/views/layout/header.jade, imports/stylesheets/events/event.import.styl, imports/stylesheets/events/eventContent.import.styl, imports/stylesheets/events/eventFiltration.import.styl, imports/stylesheets/events/eventNav.import.styl, imports/stylesheets/events/events.import.styl, imports/stylesheets/events/resolvedIncidents.import.styl, imports/stylesheets/extractIncidents.import.styl, imports/stylesheets/footer.import.styl, imports/stylesheets/globals.import.styl, imports/stylesheets/header.import.styl, imports/stylesheets/incidents/incidentList.import.styl, imports/stylesheets/index.styl, imports/stylesheets/navTabs.import.styl, imports/stylesheets/variables.import.styl, tests/features/incidents.feature, tests/features/step_definitions/incidents_steps.coffee
Styles the event page subnav.
[PT Story](https://www.pivotaltracker.com/story/show/148836701)
=> Event page sub nav

client/controllers/events/eventFiltration.coffee, client/views/events/eventFiltration.jade, imports/stylesheets/events/eventFiltration.import.styl, imports/stylesheets/globals.import.styl
[PT Story](https://www.pivotaltracker.com/story/show/148836467)
=> Add location filtration to event page

client/controllers/events/eventAffectedAreas.coffee, client/controllers/events/eventFiltration.coffee, client/controllers/events/eventResolvedIncidents.coffee, client/controllers/incidentReports/extractIncidents.coffee, client/controllers/incidentReports/incidentModal.coffee, client/controllers/intervalDetailsModal.coffee, client/views/events/eventAffectedAreas.jade, client/views/events/eventResolvedIncidents.jade, client/views/incidentReports/extractIncidents.jade, client/views/intervalDetailsModal.jade, imports/incidentResolution/incidentResolution.coffee, imports/incidentResolution/resolver.test.coffee, imports/stylesheets/maps/affectedAreas.import.styl, methods/incidentReports.coffee
Story: https://www.pivotaltracker.com/story/show/149399077
=> Add markers to affected areas map

client/controllers/addGeonameModal.coffee, client/controllers/incidentReports/incidentForm.coffee, client/controllers/locationSelect2.coffee, client/controllers/select2.coffee, client/views/incidentReports/incidentForm.jade, client/views/locationSelect2.jade, client/views/select2.jade, imports/utils.coffee, server/methods.coffee
This makes it so the locationSelect2 template uses the generic select2 template. It also fixes a bug where geoname lookup service urls passed in as environment vars wouldn't be used and it fixes some bugs that caused the "values" reactive vars used in select2 templates to have incorrect values.
=> Refactor location select2

client/controllers/incidentReports/incidentForm.coffee
Fixes [this bug](https://www.pivotaltracker.com/story/show/148583391) — Checks if incident has locations before mapping.
=> Fix add new incident - check if incident has locations

client/controllers/events/eventDetails.coffee, client/controllers/events/eventReferences.coffee, client/helpers.coffee, client/views/events/eventReferences.jade, imports/stylesheets/events/event.import.styl, imports/stylesheets/events/eventTables.import.styl, imports/stylesheets/tables.import.styl, imports/utils.coffee
Story: https://www.pivotaltracker.com/story/show/149137839
=> Add content to event references tab

imports/reactiveTable.coffee
[PT Bug](https://www.pivotaltracker.com/story/show/149766871)
=> Fix issues with how reactive table field settings are created

client/controllers/events/eventFiltration.coffee, client/controllers/intervalDetailsModal.coffee, client/controllers/slider.coffee
@nathanathan I suppose the dates in the table are correct? (those formatted in formatDateRange). So I also use UTC to display the dates in the filtration area.
=> Align dates in filtration with dates in incident

client/controllers/events/eventAffectedAreas.coffee
[PT Story](https://www.pivotaltracker.com/story/show/149695433)
=> Update affected areas marker color to increase contrast

client/views/events/eventFiltration.jade, imports/stylesheets/events/eventFiltration.import.styl
[PT Bug](https://www.pivotaltracker.com/story/show/149846442)
=> Restrict height of event filter locationn list

client/controllers/events/eventFiltration.coffee, client/views/events/eventFiltration.jade
[PT Story](https://www.pivotaltracker.com/story/show/149672783)
=> Always show slider to keep UI consistent

client/controllers/events/curatedEvent.coffee, client/controllers/events/eventIncidentReports.coffee, client/views/events/curatedEvent.jade, client/views/events/eventIncidentReports.jade, client/views/noResults.jade, imports/stylesheets/events/event.import.styl, imports/stylesheets/events/eventContent.import.styl, imports/stylesheets/events/resolvedIncidents.import.styl, imports/stylesheets/fonts.import.styl, imports/stylesheets/utils.import.styl
Makes improvements to UX by adding no results messages and loading indicators to let user know filters have been considered in the results.
=> Event filtration no results

client/controllers/events/eventIncidentReports.coffee, client/controllers/incidentReports/incidentForm.coffee, client/views/articles.jade, client/views/incidentReports/incidentForm.jade, imports/utils.coffee, server/oneWaySync.coffee, server/publications.coffee
This resolves the document title issue [here](https://www.pivotaltracker.com/story/show/148683711) and a few other issues described in the commit messages.
=> Misc. bug fixes

imports/utils.coffee, server/updaters.coffee
This removes invalid date ranges where the end occurs before the start and prevents them from being created. It also changes the measure of date precision to the length of the date interval.
=> Remove invalid dates

client/controllers/events/eventAffectedAreas.coffee, client/views/events/eventAffectedAreas.jade, imports/stylesheets/maps/map.import.styl, imports/stylesheets/variables.import.styl
Story: https://www.pivotaltracker.com/story/show/149491409
=> Add legend to affected areas map

client/controllers/events/createEventModal.coffee, client/controllers/events/eventsTable.coffee, client/controllers/events/location.coffee, client/views/events/eventDetails.jade, imports/stylesheets/events/eventDetails.import.styl
Story: https://www.pivotaltracker.com/story/show/149923797
=> Show smart event query details

client/controllers/events/eventIncidentReports.coffee, client/controllers/events/eventResolvedIncidents.coffee
Story: https://www.pivotaltracker.com/story/show/149903339
=> Fix incident details row removal

client/controllers/events/curatedEvent.coffee, client/controllers/events/eventFiltration.coffee, client/controllers/events/eventIncidentReports.coffee, client/controllers/slider.coffee, client/views/events/curatedEvent.jade, client/views/events/eventFiltration.jade, client/views/events/eventIncidentReports.jade, client/views/incidentReports/addIncidentReport.jade, imports/stylesheets/events/eventContent.import.styl, imports/stylesheets/events/eventFiltration.import.styl, imports/stylesheets/maps/affectedAreas.import.styl, imports/stylesheets/mixins.import.styl, imports/stylesheets/modals/modals.import.styl, imports/stylesheets/popup.import.styl, imports/stylesheets/select2.import.styl, imports/stylesheets/utils.import.styl, packages/_tests/fixtures.coffee, tests/features/events.feature, tests/features/step_definitions/events_steps.coffee, tests/features/step_definitions/incidents_steps.coffee
Adds a test scenario which tests each filtration section. Thoughts on adding a scenario which combines several filter properties?
Also adds:
- A clear button to clear all the filters
- Made the incident list reactive so when a new incident is added, it will reactively appear in the list
- Only add the location query if default range and selected not equal
[PT Chore](https://www.pivotaltracker.com/story/show/149213109)
=> Event page tests

client/controllers/events/curatedEvent.coffee, client/controllers/smartEvents/smartEvent.coffee, client/views/events/curatedEvent.jade, client/views/smartEvents/smartEvent.jade, imports/stylesheets/events/eventFiltration.import.styl
[PT Bug](https://www.pivotaltracker.com/story/show/149962130)
=> Add veil to filters if no incidents

client/controllers/notification.coffee, client/views/notification.jade, imports/stylesheets/header.import.styl, imports/stylesheets/notification.import.styl
[PT Chore](https://www.pivotaltracker.com/story/show/144129595)
=> Update notification - now appears at top of viewport

client/controllers/feeds.coffee, client/controllers/notification.coffee, client/views/feeds.jade, imports/schemas/feed.coffee, imports/stylesheets/notification.import.styl, imports/stylesheets/variables.import.styl, imports/ui/notification.coffee, methods/feeds.coffee, server/updaters.coffee, tests/features/feeds.feature
[PT Bug](https://www.pivotaltracker.com/story/show/144114949)
=> Do not allow users to delete default feed

client/controllers/events/eventIncidentReports.coffee, client/controllers/incidentReports/incidentForm.coffee, client/controllers/incidentReports/incidentReport.coffee, client/controllers/select2.coffee, client/helpers.coffee, client/views/incidentReports/incidentCount.jade, client/views/incidentReports/incidentForm.jade, client/views/incidentReports/incidentReport.jade, imports/incidentResolution/convertAllIncidentsToDifferentials.coffee, imports/schemas/incidentReport.coffee, imports/stylesheets/forms/forms.import.styl, imports/stylesheets/incidents/incidentForm.import.styl, imports/stylesheets/utils.import.styl, imports/utils.coffee, server/updaters.coffee, tests/features/incidents.feature, tests/features/step_definitions/incidents_steps.coffee
Story: https://www.pivotaltracker.com/story/show/150013165
This also adds a type property to incidents which should be useful for reducing the amount of type inference code in the future.
=> Update incident type selector, add active cases type

server/updaters.coffee
[PT Chore](https://www.pivotaltracker.com/story/show/150526265)
=> Remove alternateLocations from incident locations

imports/stylesheets/tooltips.import.styl
[PT Bug](https://www.pivotaltracker.com/story/show/151052811)
=> Fix z-index issue with incident form tooltips

client/controllers/events/eventIncidentReports.coffee, client/controllers/events/eventResolvedIncidents.coffee, client/controllers/incidentReports/suggestedIncidentsModal.coffee, client/views/incidentReports/incidentForm.jade, client/views/incidentReports/suggestedIncidentsModal.jade, client/views/intervalDetailsModal.jade, imports/constants.coffee, imports/incidentResolution/incidentResolution.coffee, imports/incidentResolution/resolver.test.coffee, imports/nlp.coffee, imports/schemas/incidentReport.coffee, imports/utils.coffee
This adds a simpler incident resolution method that is much more performant than the linear programming based method. It also changes the formatDateRange function to display inclusive date ranges where the final date is part of the duration.
=> Implement fast incident resolution method

client/controllers/incidentReports/addIncidentReport.coffee, client/controllers/incidentReports/incidentModal.coffee, client/controllers/incidentReports/suggestedIncidentsModal.coffee, client/views/incidentReports/incidentModal.jade, client/views/incidentReports/suggestedIncidentModal.jade, imports/nlp.coffee, server/updateAutoEvents.coffee
Pivotal Story: https://www.pivotaltracker.com/story/show/149929761
=> Add delete button to incident modals

imports/incidentResolution/activeCases.test.coffee, imports/incidentResolution/convertAllIncidentsToDifferentials.coffee, imports/incidentResolution/incidentResolution.coffee, imports/incidentResolution/resolver.test.coffee, server/router.coffee
This uses a exponential decay function applied at daily time-steps to determine the number of active cases. The decay parameter of current set based on a hard coded 14 day case length, but can be set based on specific diseases in the future.
=> Add active case computation
