ecohealthalliance/eidr-connect

client/controllers/geolocations.coffee
client/stylesheets/globals.import.styl
client/views/userEvent.jade
collections/geolocations.coffee

I restyled the location section so the layout matches the articles section. Now each location link expands a details section that contains the geonames link, the user who added it, and the date it was added. The delete button still looks weird on extra small view ports though. But I didn't want to make it fill all 12 columns because that looked even more cluttered.
I keep using styling from the comments stylesheet for these sections. I think at some point it should be renamed/rewritten to describe event sections without the naming being specific to comments.

Create audit trail for event locations

---

client/controllers/userEvent.coffee
client/router.coffee
client/stylesheets/header.import.styl
client/views/userEvent.jade
collections/userEvents.coffee

I combined the edit and delete options into a dropdown menu under a button that says "Admin Options". I don't like that the dropdown menu covers the event name when it's open, maybe we can find somewhere else to put the button. I'm not sure what the reason for an event being deleted would be so I didn't really see a need to do a soft delete at this point in time.

Admins can delete EIDR C events

---

client/controllers/article.coffee
client/controllers/articles.coffee
client/controllers/geolocations.coffee
client/controllers/userEvent.coffee
client/router.coffee
client/views/createEvent.jade
client/views/locationSelect2.jade
client/views/userEvent.jade
collections/articles.coffee
collections/geolocations.coffee
collections/userEvents.coffee

Since a source article must be chosen when adding a location, I hid the location form when no articles have been added to the event yet and took away the ability to add multiple locations at once on that form. The sources are listed in the expandable location details section and can be edited there as well. When an article is removed, it's references are also removed from all locations for that event. If a location has only the removed article as its source, the location is deleted as well.

Save associated articles for each location

---

client/views/about.jade
client/views/contactUs.jade
client/views/splash.jade

I updated the text to reference the application using the name EIDR Connect rather than EIDR and to more closely reflect the capabilities of EIDR Connect. I also removed the methods and reference sections since I don't think they apply anymore. I'm assuming the funding acknowlegements will be pretty similar to EIDR, so while I put placeholder text for them, I just commented out what was there originally. I didn't update any images.

Rewrite EIDR Connect About Page

---

server/accounts.coffee

Creates initial admin user record based on this sample information provided via settings.json:
```
"private": {
"initial_user": {
"email": "tech@ecohealthalliance.org",
"password": "bottledwhiskeyisnogoodifitsonlynoon"
}
}
```

create initial user record upon server startup

---

client/controllers/count.coffee
client/controllers/counts.coffee
client/controllers/incidentReport.coffee
client/controllers/incidentReports.coffee
client/views/incidentReports.jade
client/views/userEvent.jade
collections/counts.coffee

I added a field for selecting the incident type, which toggles the following form element between a number input and a text input. In order to avoid database changes, I kept the case count, death count, and other specification values as separate document properties in the collection rather than having type and value fields.

Change case counts to incident reports

---

client/controllers/articles.coffee
client/controllers/eventMap.coffee

This PR prevents the clicks on the legend widget from going through to the map.
Also adds a warning toast when the user attempts to add an article which is already in the database.

prevent clicks from going through the legend container

---

client/controllers/locationList.coffee

I added a keyup event handler to the location filter that removes detail rows when a search term is entered.

Entering a location search term should close expanded rows

---

client/controllers/userEvent.coffee
client/router.coffee
client/views/userEvent.jade

The initial event page load still uses the same route and url. Clicking the tabs will change between 2 new routes I added. It's annoying how the page jumps to the top after clicking a tab but I'm not sure of how to keep that from happening.

Incident report / location tab navigation should be based on urls instead of events

---

client/controllers/incidentReport.coffee
client/views/incidentReports.jade

The status and species fields were already being displayed in the incident details but only if they had values, so I took away the if that kept them from being shown when they were blank. And if the incident isn't travel related, the travel related field is blank rather than containing X.

Add species and confirm status to incident report expanded table rows, and when travel related is not true, leave it blank instead of showing an X

---

client/controllers/userEvent.coffee
client/views/articles.jade
client/views/createAccount.jade
client/views/incidentReports.jade
client/views/sourceModal.jade
client/views/splash.jade
client/views/suggestedIncidentModal.jade
client/views/suggestedIncidentsModal.jade
client/views/userEvent.jade
imports/stylesheets/buttons.import.styl
imports/stylesheets/events.import.styl

Fixes up the customized set of bootstrap button classes.
Adds `.btn-delete` as alias for the `.btn-danger` and `.btn-confirm` for the `.btn-success`
Adds a few classes for more control over the styling of buttons:
`.btn-spacious` increases padding and font-size
`.btn-action` uppercases text (alias: `.shouting`)
Also removes `.main-btn` and `.secondary-btn` as the styles for those classes were removed at some point. Now we should use bootstraps btn syntax.
https://www.pivotaltracker.com/story/show/130077331

Fix styling and text-sive of buttons

---

client/controllers/editEventModal.coffee
client/controllers/userEvent.coffee
client/views/userEvent.jade
imports/stylesheets/_main.styl
imports/stylesheets/buttons.import.styl
imports/stylesheets/event.import.styl
imports/stylesheets/events.import.styl
imports/stylesheets/forms.import.styl
imports/stylesheets/modals.import.styl
imports/stylesheets/variables.import.styl

Moves the edit event UI elements into a modal and changes the _admin options_ dropdown to a simple button near the title.
Event selection now is accomplished via a button in the modal. The alert confirmation is replaced with a secondary modal 'page' which asks the user for confirmation.
When there is no disease or summary, the user sees button which opens modal and the appropriate input field is focused.
Cleans up some jade/css - specifically switching from camelCase classnames to hyphenated and avoiding using the double curly brackets to reference properties.
PT Story: https://www.pivotaltracker.com/story/show/130376327

Event details edit modal

---

client/controllers/articles.coffee
client/controllers/sourceModal.coffee
client/views/sourceModal.jade
collections/articles.coffee
imports/convertDate.coffee

Since the database stores the publication date in the local machine's timezone, we need to convert it to the target timezone when showing it on the edit form. I tried to use moment timezone to handle this conversion but it messed up the date time picker plugin, which relies on moment.  I also noticed that if a time isn't selected when saving, the edit form will show the time as 12:00 AM the next time it's opened. Maybe the date and time should be stored separately in the database.

EIDR-C article pub dates can be edited

---

client/controllers/suggestedIncidents.coffee
client/views/suggestedIncidentsModal.jade

The new button is in the modal footer and simply opens the new incident form modal.

Add button for adding non-suggested incident reports on incident report suggestion modal

---

client/controllers/incidentReports.coffee
imports/charts/Axes.coffee
imports/charts/Plot.coffee
imports/charts/ScatterPlot.coffee
imports/stylesheets/scatterPlot.import.styl

bugfix - https://www.pivotaltracker.com/story/show/132659361
- The plot will determine if it should show/hide the no data warning.
- improved styling
- improved center positioning 
- added transition on the opacity of the showWarn message
- misc bugfix to disable resetZoom if data is not at least one or zoom is disabled
- added transition on the opacity to the first drawing of the plot
Steps A:
1. goto the Event Map
2. click on a marker
3. click on a link to /user-event/:id
4. confirm that the warning does not appear
Steps B:
1. goto the Tracked Events
2. sort by Article Count ascending
3. click on an event to /user-event/:id
4. confirm that the warning appears for an event without data

bugfix - debounce plot.update; the plot will determine if it should show/hide the no data warning

---

client/controllers/incidentReports.coffee
client/views/incidentReports.jade
imports/charts/Plot.coffee
imports/charts/ScatterPlot.coffee
imports/stylesheets/scatterPlot.import.styl

https://www.pivotaltracker.com/story/show/132223713
This feature added an API to add/remove filters to the base plot. This allows the plot instance to apply these filters on each draw, including the default filter for the current axes domain. This simplifies a lot of complexity that may otherwise occur in the controller code trying to synchronize data state between each plot update. 
In the following example, the filtering method is given a name and method to execute. Note: the method will be bound to the plot instance.
```
addFilter('cumulative', (d) ->
// do something with a data element
```
```
removeFilter('cumulative')
```

adds filter capability to the plot and cumultive filter button

---

client/controllers/curatorEvents.coffee
client/controllers/curatorSuggestedEvents.coffee
client/views/curatorEvents.jade
client/views/curatorSuggestedEvents.jade
imports/collections/userEvents.coffee
imports/stylesheets/curator.import.styl
methods/userEvents.coffee
server/interfaces.coffee

https://www.pivotaltracker.com/story/show/132240647
- $text index on UserEvent `eventName` and `summary`
- server-side meteor method to perform the $text $search sorted by score
- reactive table that displays the suggested events 
- updates reactively based on associatedEventIdsToArticles object
Steps:
1. Visit Curators -> Inbox
2. Note: collapsible 'Suggested Events' table, matches that do not exist in 'Associated Events' will be displayed
3. Click on the `+` icon to add an event to the 'Associated Events' section
4. Click on the `-` icon to remove and event from the 'Associated Events' section
5. Note: the table updates reactively

add feature to suggest user events based on title of promed post

---

client/controllers/curatorEvents.coffee
client/controllers/curatorInbox.coffee
client/views/curatorInbox.jade
imports/stylesheets/curator.import.styl
imports/stylesheets/event.import.styl
imports/stylesheets/tables.import.styl
imports/stylesheets/variables.import.styl
methods/curatorSources.coffee
methods/promedPosts.coffee
server/publications.coffee
server/startup.coffee

This selects the next unreviewed source when a curator marks the currently selected source as reviewed.
Also reworks how we display source details in the curator inbox:
- Uses template in jade instead of calling `Blaze.renderWithData` in the controller
- Creates a reactiveVar which tracks which source is selected (used in the reactive table and the details template)
- Notifies user that next source is being prepared or retrieved after reviewal
And cleans up the styles of the main source table
I noticed a possible issue. [This method](https://github.com/ecohealthalliance/eidr-connect/blob/master/methods/promedPosts.coffee#L29-L41) seems to overwrite some properties such as `addedDate` locally? I wanted to find a place to add a `reviewed` property and set it false to prevent having to run …

Show next source after reviewal

---

client/controllers/footer.coffee
client/views/curatorInbox.jade
imports/stylesheets/_main.styl
imports/stylesheets/curator.import.styl
imports/stylesheets/mixins.import.styl
imports/stylesheets/panes.import.styl
imports/stylesheets/utils.import.styl
imports/stylesheets/variables.import.styl

Uses the "pane" layout pattern established [in Tater](https://github.com/ecohealthalliance/tater/blob/master/packages/styles/layout.import.styl) to position the source list and details. The two panes now scroll independently.
Also:
- Hides footer to devote as much of the screen to the panes as possible
- Adds a `addBorder` mixin swiped from Tater.
- Adds variables for z-index strata
PT: https://www.pivotaltracker.com/story/show/133182923

Curator inbox positioned panes

---

client/controllers/articles.coffee
client/controllers/curatorEvents.coffee
client/controllers/incidentReport.coffee
client/controllers/incidentReports.coffee
client/controllers/sourceModal.coffee
client/controllers/suggestedIncidents.coffee
client/views/articles.jade
client/views/incidentReports.jade
imports/utils.coffee
server/cleanUrls.coffee
server/dbUtils.coffee
server/indexes.coffee
server/interfaces.coffee

https://www.pivotaltracker.com/story/show/131123351
- adds startup methods to clean urls from the substrings `https?` and `(www.)?`
Example: http://www.promedmail.org/post/abc -> promedmail.org/post/abc
Steps:
1. Drop all `articles`, `counts`, and `curatorSources` collections from mongo
2. Perform mongorestore from backup that contains urls/links that need cleaned
2a. Extract a backup from AWS (this will create the directory `/var/log/dump/eidr-connect`)
2b. Change directories `cd /var/log/dump/eidr-connect`
2c. Run mongorestore `mongorestore -d eidr-connect .`
3. Verify that urls contain `https?` and `(www.)?`
4. Start meteor server
4a. Watch for output to stdout about bulkUpdate nModified for each collection
4b. Notice `curatorSources` falls back to single item updates due to its use of …

adds feature to clean urls

---

client/controllers/curatorEvents.coffee
client/controllers/curatorSuggestedEvents.coffee
client/views/curatorEvents.jade
client/views/curatorSuggestedEvents.jade
imports/stylesheets/curator.import.styl

Adds a toggle to the suggested events header to show and hide the associated table.
Slight refactoring to the existing toggle both in the styles and controller.
PT: https://www.pivotaltracker.com/story/show/133300025

Add visibility toggle for suggested events and refactor existing

---

client/controllers/articles.coffee
client/controllers/curatorInbox.coffee
client/controllers/incidentForm.coffee
client/controllers/incidentModal.coffee
client/controllers/incidentReport.coffee
client/controllers/incidentReports.coffee
client/controllers/locationList.coffee
client/views/incidentReports.jade
imports/stylesheets/buttons.import.styl
imports/stylesheets/event.import.styl
imports/stylesheets/globals.import.styl
imports/stylesheets/tables.import.styl
imports/ui/helpers.coffee
methods/articles.coffee

Updates the Incident Report details area like so:
It looks like there's a bunch of changes but its mostly cleaning up code styling. Like using `'` instead of `"`, removing excessive curly brackets for object declarations, etc.
We probably need to establish common patterns for stuff like this and establish a JSLint file. 
I noticed we use 3 different naming conventions to refer to the template instance in events: `instance`, `template` and `templateInstance`. I think in recent projects we've used `instance`. Maybe we should fix all of these at some point?
(layout may break on smaller screens — I can update those styles in another PR)
PT Chore: https://www.pivotaltracker.com/story/show/133691167

Event page incident details styles

---

.meteor/packages
.meteor/versions
client/controllers/incidentReports.coffee
imports/charts/Axes.coffee
imports/charts/Errors.coffee
imports/charts/Grid.coffee
imports/charts/Group.coffee
imports/charts/Node.coffee
imports/charts/Plot.coffee
imports/charts/RectMarker.coffee
imports/charts/ScatterPlot.coffee
imports/charts/SegmentMarker.coffee
imports/charts/Tooltip.coffee
imports/charts/Zoom.coffee
imports/stylesheets/scatterPlot.import.styl
package.json

- upgraded to d3v4 via `npm`
Updates to the ScatterPlot interface:
- created concept of a Group which contains Nodes
- each node should be an instanceof `Node`
- each group should be an instanceof `Group`
- throws errors `InvalidNodeError` and `InvalidGroupError`
- `plot.update()` accepts an array or an object
- if its an array: a default group will be created and all nodes will be appended
- if its an object: each key will be a new group and its value as an array of nodes
- the creation of nodes and groups is transparent to keep the API simple
- when constructing the ScatterPlot, there is an option for `group`, which allows binding an event handler during onEnter.
```
group: {
onEnter: () ->
@.group.on('mouseover', () =>
if @plot.tooltip
@plot.tooltip.mouseover(@, d3.event.pageX, …
```

scatterPlot markers as line segments

---

client/controllers/incidentDeleteModal.coffee
client/controllers/incidentReports.coffee
client/views/incidentDeleteModal.jade

https://www.pivotaltracker.com/story/show/133695987
Steps:
1. Click Tracked Events
2. Sort by # incidents descending
3. Choose Event with # incidents > 0
4. Click the toggle on the Incidents table
5. click the trash icon
6. choose delete

change incident delete alert into a modal

---

package.json
run-tests.sh

Example:
```
./run-tests.sh --app_uri=http://127.0.0.1 --app_port=13000 --mongo_host=127.0.0.1 --mongo_port=13001 --prod_db=eidr-connect --test_db=eidr-connect-test
```

upgrade chimp, allow for args to run-tests.sh

---

client/controllers/layout.coffee
client/startup.coffee

right now if there are two modals on a page the "escape to close" functionality will not work.

fixing escape to close modals bug

---

.meteor/packages
.meteor/versions
client/controllers/incidentReports/incidentReports.coffee
imports/charts/Plot.coffee
imports/charts/ScatterPlot.coffee
packages/_tests/package.js
start-test-server.sh
tests/features/incident.feature
tests/features/step_definitions/incident_steps.coffee

Fixes "EIDR-C incident plot doesn't update when incident is added"
This would happen when a user added an incident outside the plot's current _domain filter.  The fix  was to keep track of when new groups are added during the merge operation so that the domain filter can be temporarily disabled.
Integration tests have been added.
https://www.pivotaltracker.com/story/show/135206307

Fix scatter plot update

---

client/views/events/userEvents.jade
imports/stylesheets/ui.import.styl

Fixes a small visual bug that was causing the elements in the events header (the "tracked events" heading, button, and search input) to break into incorrect positions.
[PT Bug](https://www.pivotaltracker.com/story/show/135662111)

Fix events header UI on small screens

---

start-test-server.sh
tests/features/step_definitions/admin_steps.coffee

This PR fixes the issue with the git error `error: pathspec 'origin/some-branch-name' did not match any file(s) known to git.` 
Note: Since the container is started with the `command: ['bash', '-c', '/home/meteor/eidr-connect/start-test-server.sh --mongo_host=mongodb --is_docker=true']`, the script start-test-server.sh is already running, so if this file is modified by the branch, doing `git checkout origin/some-branch-name` will not take effect during the current jenkins job.
One workaround for this is to log into jenkins, start a containter for the image eidr-connect-test:latest, perform a `git fetch && git checkout origin/some-branch-name && git checkout -b some-branch-name`, exit the container and update the image through `docker commit`.  
Another alternative would be to alter the …

Fix start-test-server script to perform git fetch prior to checkout

---

.meteor/packages
.meteor/versions
client/controllers/curatorInbox/curatorUserStatus.coffee
client/views/curatorInbox/curatorEvents.jade
client/views/curatorInbox/curatorUserStatus.jade
methods/userStatus.coffee
server/accounts.coffee
server/publications.coffee
server/startup.coffee

This PR adds the meteor package `mizzao:user-status` to keep track of which users are online.  It adds a property to the user document called 'status'.  The client then runs reactive queries against users whose status.online == true and curatorInboxSourceId == the current selectedSourceId.
The result of the queries is a count.  If the count is greater than 1 (accounting for their own status), then a bootstrap badge is displayed with the number of online users within the header of the `Associated Events`.
When the template isRemoved, the meteor method that sets curatorInboxSourceId is called again with null, to update that the user is no longer active on that curator source. 
The server also guards against users who loose connectivity and go offline by performing a server-side observe of …

Add feature to display user status for curator inbox

---

client/controllers/curatorInbox/curatorInbox.coffee

This happens when the user click on a startDate and does not choose an endDate, then clicks [Apply]. The code would see endDate is null and then set endDate as an object reference to startDate, thus startDate === endDate.  The fix is to make endDate as a copy of startDate and set its time to a millisecond before midnight.
- make the endDate a copy of startDate at a millisecond before midnight
https://www.pivotaltracker.com/story/show/134378881

fix curatorInbox date filter bug

---

client/controllers/cancelConfirmation/cancelConfirmationModal.coffee
client/controllers/cancelConfirmation/cancelConfirmationModalBody.coffee
client/controllers/incidentReports/suggestedIncidentsModal.coffee
client/views/cancelConfirmation/cancelConfirmationModal.jade
client/views/cancelConfirmation/cancelConfirmationModalBody.jade
client/views/incidentReports/suggestedIncidentModal.jade
client/views/incidentReports/suggestedIncidentsModal.jade
client/views/modalConfirmCloseButton.jade
client/views/sourceModal.jade
imports/stylesheets/cancelConfirmation.import.styl
imports/stylesheets/index.styl

https://www.pivotaltracker.com/story/show/134380381
To test:
1.  Login to the app and navigate to [Tracked Events]
2. Click on one of the events in the table
3. Click on the [Add Sources] button
4. Choose a `Suggested Article` by clicking on the text then click [Save]
5. Wait for the article to be processed...
6. Click on a red underlined text, wait for the next modal, then click [Confirm]
7. Note: that the number of accepted incidents has changed
8. Try to cancel/close the modal.
9. Note: a confirmation modal appears

add feature to confirm closing suggestedIncidentsModal

---

client/controllers/incidentReports/suggestedIncidentsModal.coffee
client/views/createEventModal.jade
client/views/deleteConfirmation/deleteConfirmationModal.jade
client/views/events/editEventDetailsModal.jade
client/views/incidentReports/incidentModal.jade
client/views/incidentReports/suggestedIncidentModal.jade
client/views/incidentReports/suggestedIncidentsModal.jade
client/views/sourceModal.jade
imports/stylesheets/curator.import.styl
imports/stylesheets/globals.import.styl
imports/stylesheets/incidents/incidents.import.styl
imports/stylesheets/mixins.import.styl
imports/stylesheets/modals.import.styl

The problem ([documented in this bug](https://www.pivotaltracker.com/story/show/136069771)) was happening because the `modal-open` class was being removed from the body when the _add source_ modal closed but after the _suggested incident report_ modal added it back.
Makes the _suggested incidents report_ modal stretch to the height of the viewport (and gives a min-height) and adds gradients on the top and bottom of the text window to imply additional content beyond.

Fix unscrollable modals

---

client/controllers/articles.coffee
client/controllers/curatorInbox/curatorEvents.coffee
client/controllers/curatorInbox/curatorInbox.coffee
client/controllers/events/locationList.coffee
client/controllers/events/userEvents.coffee
client/controllers/maps/mapFilters.coffee
client/controllers/searchInput.coffee
client/views/articles.jade
client/views/curatorInbox/curatorEvents.jade
client/views/curatorInbox/curatorInbox.jade
client/views/events/locationList.jade
client/views/events/userEvents.jade
client/views/maps/mapFilters.jade
client/views/searchInput.jade
imports/stylesheets/curator.import.styl
imports/stylesheets/events/event.import.styl
imports/stylesheets/forms/forms.import.styl
imports/stylesheets/index.styl
imports/stylesheets/searchInput.import.styl

I went ahead and created a single template for all the search inputs. I figured it would reduce a fair amount of repetition with clearing inputs and force us into a consistent search UI/UX.
The template receives an object with options including:
- `textFilter`: either a `reactiveVar` or `ReactiveTableFilter`
- `id` the id associated with the element and `ReactiveTableFilter` if its passed
- `props` if a `ReactiveTableFilter` is not passed, one will be created with the `id` and `props` which is an array
- `toggleable`If set to true, the input will be initially hidden and appear when the search icon is clicked. When the user clicks on the search icon within the input, the input returns to its hidden state.
- `placeholder` defaults to 'Search'
- `classes` classes which will be applied to the …

Clear searches

---

client/controllers/incidentReports/suggestedIncidentsModal.coffee

Fixes https://www.pivotaltracker.com/story/show/136212851
The `incidentCollection` is now emptied after successful save to the remote.

fix confirm modal appearing after suggested incidents have been saved 

---

client/controllers/curatorInbox/curatorEvents.coffee
client/controllers/curatorInbox/curatorSuggestedEvents.coffee
client/views/curatorInbox/curatorEvents.jade

Looks like at some point the instantiation of the `suggestedEventsHeaderState` reactiveVar made its way into an `@autorun` so it's value was being reset when a collection updated.
[PT Bug](https://www.pivotaltracker.com/story/show/136383865)

Fix bug where associated suggested events not removed from table

---

imports/ui/inlineDateRangePicker.coffee

Before this update, the abbreviation (down to 1 letter) was replaced after the user selected a new month. Modifies the click events of next and prev buttons to abbreviate the months
[PT Bug](https://www.pivotaltracker.com/story/show/136389589)

Update createInlineDateTangePicker to abbreviate months

---

client/controllers/curatorInbox/curatorSuggestedEvents.coffee

Right now events that are already associated show under suggested events

filtering out associated events from suggested events

---

.meteor/versions
client/controllers/curatorInbox/curatorUserStatus.coffee
client/views/curatorInbox/curatorEvents.jade
client/views/curatorInbox/curatorInbox.jade
client/views/curatorInbox/curatorUserStatus.jade
imports/stylesheets/curator.import.styl
methods/userStatus.coffee

Also rethinks the indicator, changes it from a count badge to an eye icon and relocates it to next to the source title.
I think explicitly showing the count is less important than indicating there are other curators actively viewing the same source.
Also ensure the tooltip shows when the template/view is destroyed and added back.
[PT Bug](https://www.pivotaltracker.com/story/show/136513111)

Fix flickering user indicator badge

---

client/controllers/curatorInbox/curatorUserStatus.coffee

Re-instantiate the tooltip when the source changes in addition to the otherActiveUser state.

Instantiate tooltip for other active users when sourceid changes

---

Dockerfile

Since we are using `fs.readFile path.join(process.env.PWD, 'revision.txt')` to read the txt file we need to put the file in the working directory rather than `/`

changing path that revision.txt is copied to

---

imports/stylesheets/datepicker.import.styl

Small fix to the single calendar date range picker — centers it in the UI by removing the right margin/padding.

Remove right margin on single date range picker

---

client/controllers/incidentReports/incidentForm.coffee
client/views/incidentReports/incidentForm.jade
client/views/incidentReports/incidentReport.jade
client/views/sourceModal.jade
imports/schemas/incidentReport.coffee
imports/stylesheets/events/incidentDetails.import.styl
imports/stylesheets/forms/forms.import.styl
imports/stylesheets/forms/suggested.import.styl
imports/stylesheets/incidents/incidentForm.import.styl
imports/stylesheets/mixins.import.styl
imports/stylesheets/pillSelector.import.styl
imports/stylesheets/sources.import.styl
imports/stylesheets/validator.import.styl
imports/utils.coffee

I grouped the IR type inputs and the child inputs appear when a type is selected. I added a grouping of checkboxes called "Integrity" which includes `cumulative` and `approximate` (`cumulative` was included in "Additional information"). Not sure if its an appropriate title, let me know what you think.
If `cumulative` or `approximate` are selected, they appear in the IR details UI like so:

Add 'approximate' property to IRs and display in details

---

imports/stylesheets/incidents/incidentForm.import.styl

The tabs had no width due to me initially using `flex 0` (my bad). Changed it to `flex 0 0 auto` which allows the elements to establish their widths naturally without growing into available space.

Fix size of incident report date tabs in safari <= 9.x.x

---

client/controllers/sourceModal.coffee
client/views/sourceModal.jade

For some reason setting the promed regex as a variable caused the `exec` function to alternately return null even when everything matched (Any ideas why this would be happening? The same behavior occurs in the console).
I also refactored the click event of suggested articles - removed the jquery code and update values of the fields using helpers.

Fix updating datetime when clicking suggested source

---

imports/stylesheets/forms/suggested.import.styl
imports/stylesheets/variables.import.styl

Breaks the UI out to a two-pane UI at 992px and above. Snippet on left and form on right:
[PT story](https://www.pivotaltracker.com/story/show/137783155)

Update Suggested IR UI - content on left and right

---

client/controllers/incidentReports/incidentForm.coffee
client/controllers/incidentReports/incidentModal.coffee
client/controllers/incidentReports/suggestedIncidentsModal.coffee
client/controllers/incidentReports/suggestedIndidentModal.coffee
client/views/incidentReports/suggestedIncidentModal.jade

I noticed in some circumstances when a location was not determined by the GRITS api, the location field was still marked as autofilled and the user could submit the form.
This PR:
- If there is no location, removes the `location` field from the `suggestedFields` array and runs the validator to mark the field as invalid.
- Refactors the removal of suggestedFields into a function.
- Validates the suggested incident form

Fix ir location autofill bug

---

client/controllers/incidentReports/incidentForm.coffee
client/controllers/sourceModal.coffee
client/views/sourceModal.jade
imports/stylesheets/datepicker.import.styl
imports/stylesheets/forms/suggested.import.styl
imports/stylesheets/sources.import.styl
imports/utils.coffee

This applies a variant of existing autofill styles to the source form. I thought that since the autofill occurs after a user action (clicking a suggested article) we can reduce the visual indication—just change the border and background of the inputs:

Style autofilled source form inputs

---

client/controllers/searchInput.coffee

The `click` and `focusin` events were conflicting with each other so i just removed the `click` event.

Fix search input component events - remove click event

---

client/controllers/curatorInbox/curatorInbox.coffee
client/views/curatorInbox/curatorInbox.jade
client/views/events/userEvent.jade
imports/stylesheets/curatorInbox.import.styl
imports/stylesheets/loading.import.styl
imports/stylesheets/panes.import.styl
imports/stylesheets/ui.import.styl

- Fixes [this bug](https://www.pivotaltracker.com/story/show/139570855) causing the UI to hang on loading when the current date is selected for filtration by setting the max date to the publish date of the latest source in the collection
- Shows the default filtration range
- Only shows the reset button when a user has changed the range
- Refactors how we show content when range changes: no longer reload the calendar
- When user selects only one date, the UI updates to reflect single-date selection (lingering range highlighting is removed)
- Shows loading indicator over only the source list — related to [this story](https://www.pivotaltracker.com/story/show/139570825)

Improve UX of date filtration in curator inbox

---

imports/charts/Axes.coffee

I suppose this probably won't be a problem because the bug only occurs when the counts are above 100,000 but I nudged the label to the left a little. If it does become a problem I suppose we could use a solution like this: https://github.com/d3/d3-axis/blob/master/README.md#axis_tickFormat

Update the position of the y-axis label

---

methods/userEvents.coffee
server/startup.coffee

This soft deletes IRs associated with deleted user events and deletes them when a user event is deleted to prevent these IRs showing with smart events.

Delete IRs of deleted events

---

imports/charts/ScatterPlot.coffee
imports/charts/Zoom.coffee

Fix for [this bug](https://www.pivotaltracker.com/story/show/140577847).
The yMax of the y-axis was not being updated when the data changed (e.g. when the cumulative button was toggled). Now when the plot us updated, the axes are as well.

Update axes when plot data is updated

---

client/controllers/incidentReports/incidentForm.coffee
client/controllers/incidentReports/incidentReports.coffee

Fixes [this bug](https://www.pivotaltracker.com/story/show/140877257).
Caused by a recent change where we pass a collection of articles to the form instead of an array.

Fix bug with showing IR edit form - get collection as array

---

client/controllers/curatorInbox/curatorInbox.coffee
client/controllers/curatorInbox/curatorSourceDetails.coffee
client/controllers/incidentReports/suggestedIncidentsModal.coffee
client/controllers/notification.coffee
client/views/curatorInbox/curatorSourceDetails.jade
imports/schemas/incidentReport.coffee
methods/incidentReports.coffee
server/publications.coffee

[PT Story](https://www.pivotaltracker.com/story/show/141164735)
Looks like there is currently no automated process for getting articles from ProMed—they are fetched when the inbox is loaded and added to the `CuratorSources` collection. So to move this along quickly, I've updated the inbox to process articles when they are clicked. The resulting incident reports are added to the collection (I made some fields in the schema optional since now some IRs may not have certain properties). The resulting UX is not really ideal because, I think, the processing time is a little too long for the user to wait. So we should think about automating this in the future.
I moved the logic associated with creating IRs from enhancements to a Meteor method so we can call it from multiple areas.
**This does …

Curator inbox get article enhancements

---

.promed-post-enhancer/app.js
client/controllers/curatorInbox/curatorSourceDetails.coffee
client/controllers/incidentReports/incidentForm.coffee
client/controllers/incidentReports/suggestedIncidentsModal.coffee
client/views/incidentReports/incidentReport.jade
imports/schemas/incidentReport.coffee
methods/articles.coffee
methods/incidentReports.coffee
server/publications.coffee
server/startup.coffee

Updates the schema of Incident Reports—changes the `url` property from an array to a string.
Updates existing IRs in database and areas were the url is referenced, updated or presented.
[PT Chore](https://www.pivotaltracker.com/story/show/141256773)

Change ir url to string

---

client/controllers/incidentReports/incidentForm.coffee
client/controllers/incidentReports/incidentModal.coffee
client/controllers/incidentReports/incidentTable.coffee
client/controllers/incidentReports/suggestedIncidentsModal.coffee
client/views/curatorInbox/curatorSourceDetails.jade
client/views/incidentReports/extractedIncidents.jade
client/views/incidentReports/incidentForm.jade
client/views/incidentReports/incidentTable.jade
client/views/incidentReports/suggestedIncidentsModal.jade
imports/stylesheets/curatorInbox.import.styl
imports/stylesheets/incidents/incidents.import.styl
imports/utils.coffee

[PT Story](https://www.pivotaltracker.com/story/show/141164797)
This is currently not reactive since we are using a local collection created when the source is processed (because I wanted to ease into adding all IRs into the db — IRs are currently not added to the db in the event page flow until they are confirmed.) Maybe we update the curator inbox IR table to use the incidents collection while implementing a future story or add a chore to do so.

Implement IR editing in curator inbox

---

imports/stylesheets/incidents/incidents.import.styl

The `background` applied to each type were overriding the viewing background given with the `viewing` class.

Highlight all annotated incident report text with yellow color

---

client/controllers/events/createEventModal.coffee
client/controllers/events/editEventModal.coffee
client/controllers/incidentReports/incidentForm.coffee
client/controllers/locationSelect2.coffee
client/controllers/select2.coffee
client/controllers/smartEvents/editSmartEventDetailsModal.coffee
client/controllers/smartEvents/smartEvent.coffee
client/views/events/createEventModal.jade
client/views/events/editEventDetailsModal.jade
client/views/events/summary.jade
client/views/incidentReports/incidentForm.jade
client/views/incidentReports/incidentReport.jade
client/views/locationSelect2.jade
client/views/select2.jade
client/views/smartEvents/editSmartEventDetailsModal.jade
client/views/smartEvents/smartEventSummary.jade
imports/schemas/incidentReport.coffee
imports/schemas/smartEvent.coffee
imports/schemas/userEvent.coffee
imports/utils.coffee
methods/incidentReports.coffee
server/startup.coffee

This also updates the database to store disease ontology ids and labels instead of free-text values. I am leaving the free-text disease field in the database for now incase we find problems with the automatic mappings of free-text names to disease ontology names.

Make incident report disease fields use values selected from disease ontology

---

client/controllers/curatorInbox/curatorSourceDetails.coffee
server/publications.coffee

Sorts the IRs in tables.
Probably should remove [this addition](https://github.com/ecohealthalliance/eidr-connect/blob/b490c53197c8575e6521bd92b3dde6cd01727752/imports/ui/annotation.coffee#L5-L8) in #314 in favor of sorting when we query the collection?
[PT story](https://www.pivotaltracker.com/story/show/142338945)

Sort incidents in curator IR tables by start offset

---

client/controllers/curatorInbox/curatorSourceDetails.coffee
client/controllers/incidentReports/extractIncidents.coffee
client/controllers/incidentReports/suggestedIncidentsModal.coffee
client/startup.coffee
client/views/incidentReports/suggestedIncidentsModal.jade
imports/stylesheets/incidents/incidentTable.import.styl
imports/stylesheets/incidents/incidents.import.styl
imports/stylesheets/variables.import.styl

[PT Bug](https://www.pivotaltracker.com/story/show/142938953)
- Fixes styling of Extracted Incidents modal and improves UI — breaks from tabbed interface into side-by-side at 1200px.
- Removes wideUI logic from the curator inbox details controller. Recent changes to the UI have made it unnecessary.

Extract incidents fix styles

---

client/controllers/curatorInbox/curatorSourceDetails.coffee
client/controllers/curatorInbox/sourceIncidentReports.coffee
client/controllers/incidentReports/incidentTable.coffee
client/controllers/incidentReports/suggestedIncidentModal.coffee
client/views/curatorInbox/curatorSourceDetails.jade
client/views/incidentReports/incidentTable.jade
imports/stylesheets/incidents/incidents.import.styl

I suppose minimongo can't handle sorting like this: `sort: 'annotations.case.0.textOffsets.0': 1` I replaced it with `_.sortBy` to fix the bug where newly added Incidents were ending up at the bottom of the list.
I also noticed we, at some point, started to set the incidents loaded flag before the subscription is ready so I fixed that.
[PT Bug](https://www.pivotaltracker.com/story/show/143314903)

Curator inbox sort incidents after addition

---

client/controllers/curatorInbox/curatorSourceDetails.coffee
client/views/curatorInbox/curatorSourceDetails.jade
imports/stylesheets/curatorInbox/curatorInbox.import.styl

One of the issues the proMed folks had I think was related to them trying to view and process a document with an invalid URL (http://www.promedmail.org/post/undefined in this case). Not sure how it happened but I suppose we need to check for this on submission? Or just stay with letting it fail gracefully like this PR does.
I think this is just an initial step—seems like we should allow the curator to edit or delete the document? Maybe both?

Show warning if document does not contain text content

---

client/router.coffee
client/views/layout/header.jade
server/oneWaySync.coffee
server/publications.coffee
server/startup.coffee
server/updaters.coffee
tests/features/incident.feature
tests/features/sources.feature
tests/features/step_definitions/events_steps.coffee
tests/features/step_definitions/sources_steps.coffee

The event-map page needs to be refactored. It is subscribing to too many incidents crashing the server.
The startup optimizations work by asynchronously validating incident reports and only running database update code if a dataVersion property I added indicates the database needs the update.
I also made some modifications to the tests to ignore the scenarios we expect to fail and not try click the hidden enhance button.

Optimize startup and disable broken event-map page

---

client/controllers/curatorInbox/curatorSourceDetails.coffee
client/controllers/curatorInbox/sourceIncidentReports.coffee
client/controllers/incidentReports/annotatedContent.coffee
client/controllers/incidentReports/incidentTable.coffee
client/controllers/incidentReports/suggestedIncidentModal.coffee
client/views/curatorInbox/curatorSourceDetails.jade
client/views/curatorInbox/sourceIncidentReports.jade
client/views/incidentReports/incidentTable.jade
client/views/incidentReports/suggestedIncidentModal.jade

Pivotal story: https://www.pivotaltracker.com/story/show/145665197
This also fixes a bug where the suggestedIncident modal's reject button wasn't working.

Hide rejected incidents table

---

client/controllers/incidentReports/annotatedContent.coffee
client/controllers/incidentReports/incidentModal.coffee
client/controllers/incidentReports/incidentReports.coffee
client/controllers/incidentReports/incidentTable.coffee
client/controllers/incidentReports/newIncidentFromSelection.coffee
client/controllers/incidentReports/suggestedIncidentModal.coffee
client/controllers/incidentReports/suggestedIncidentsModal.coffee
client/views/downloadCSVModal.jade
client/views/events/createEventModal.jade
client/views/events/editEventDetailsModal.jade
client/views/incidentReports/incidentModal.jade
client/views/incidentReports/suggestedIncidentModal.jade
client/views/incidentReports/suggestedIncidentsModal.jade
client/views/smartEvents/editSmartEventDetailsModal.jade
client/views/sourceModal.jade
imports/stylesheets/modals/modals.import.styl
imports/stylesheets/ui.import.styl
methods/incidentReports.coffee
server/publications.coffee
tests/features/incident.feature
tests/features/step_definitions/incident_steps.coffee

[Fixes this bug](https://www.pivotaltracker.com/story/show/145504331)
Looks like there are 19 incidents that have both `cases` and `deaths` properties but most, if not all, instances have the same value. This will cause issues if the incidents are edited in the future. We may want to review these incidents and manually change the type?

Remove existing incident type props when incident types changes

---

client/controllers/articles.coffee
client/views/articles.jade
client/views/curatorInbox/curatorSourceDetails.jade
imports/stylesheets/curatorInbox/headers.import.styl
imports/stylesheets/events/sources.import.styl
imports/stylesheets/globals.import.styl

[PT Bug](https://www.pivotaltracker.com/story/show/146606131)
Also adds counts for document locations and incidents in document details and incident count in inbox document details.
I also updated the wording of a few helpers from source to document to I wonder if we should start renaming references to documents in the code? We refer to them as _documents_, _articles_ and _sources_. 😕

Fix unaccepted incidents showing in doc details 146606131

---

client/controllers/resolvedIncidentsPlot.coffee
client/views/intervalDetailsModal.jade
client/views/resolvedIncidentsPlot.jade
imports/incidentResolution/LocationTree.test.coffee
imports/incidentResolution/incidentResolution.coffee
imports/stylesheets/events/event.import.styl
tests/features/step_definitions/curator_inbox_steps.coffee

In the resolved incident plot the top locations previously used the largest rate from the sub-location if no rate was defined for the top location. This lead to rates being lower than they should be because the rates from disjoint sub-locations should have been combined. This PR fixes the issue by ensuring top location rates are defined in every sub-interval.
This also improves the interval detail view by displaying sub-components hierarchically.

Fix top level locations not combining rates from all sub-locations

---

imports/stylesheets/forms/suggested.import.styl

This took a good bit of digging. Applies `will-change: transform` to scrollable elements within the `suggestedIncidentModal` which tells the browser to expect changes to these elements.

Fix incident modal content repositioning 147827315

---

client/controllers/incidentReports/incidentSecondaryDetails.coffee
client/views/incidentReports/incidentSecondaryDetails.jade
imports/stylesheets/incidents/incidentList.import.styl
imports/utils.coffee

There was an edge case where if a location did not have a name property, an error would be thrown and a phantom space would appear in the UI.
Also fixes an issue which disabled the incident detail toggle when the incident had events but no locations.
[PT Bug](https://www.pivotaltracker.com/story/show/148483127)

Fix bugs related to location not having name

---

imports/ui/annotation.coffee
imports/ui/snippets.coffee
imports/utils.coffee
server/methods.coffee

This makes some updates to the incident report suggestion code to handle some changes to the resolvedKeyword data returned by the GRITS API. This also adds species suggestions and fixes a couple bugs. The annotated content's end offset was off by one and a environment variable defined constant was being used on the client side where it is unavailable.

Handle GRITS API changes

---

client/views/events/eventResolvedIncidents.jade
imports/stylesheets/events/resolvedIncidents.import.styl

Small update to the resolved incidents plot that adds a veil and brings the loading animation to the front in space.
[PT Bug](https://www.pivotaltracker.com/story/show/149273195)

Update loading indicator of resolved plot - add veil

---

imports/schemas/incidentReport.coffee
methods/incidentReports.coffee
server/autoprocess.coffee
server/startup.coffee
server/updaters.coffee

This marks incidents from pre December 2016 events as cumulative if they report more than 50 cases in a day.
This also prevents validation from running during a database update.

Add incident modified date, fix unmarked cumulative counts

---

imports/ui/deletion.coffee
server/oneWaySync.coffee
server/publications.coffee
server/router.coffee
server/startup.coffee

This updates the one way sync code to only sync data from curated events. The database is becoming too large to sync all the data.

Only sync curated event data

---

client/controllers/events/eventFiltration.coffee
client/views/incidentReports/suggestedIncidentsModal.jade

Prior to this update [Object] was being displayed in the species column of the extract-incidents table and the location filter was not showing all the available locations when initially loaded.

Fix species name bug and location filter bug

---

imports/stylesheets/events/eventContent.import.styl

I forgot to position the `event--content` element relatively so the veils will be contained.

Do not cover filters when no incidents

---

client/controllers/events/eventAffectedAreas.coffee

Not sure if this is necessary?...it only seems to be a problem on [this event](https://eidr-connect.eha.io/events/curated-events/gfnPs88SBb3aaBeeA).

Add incident to incident marker area if not in array

---

client/controllers/curatorInbox/curatorInbox.coffee
client/controllers/events/eventFiltration.coffee
client/controllers/events/smartEvent/editSmartEventDetailsModal.coffee
client/controllers/incidentReports/incidentForm.coffee
client/views/events/autoEvent/autoEventDetails.jade
client/views/events/eventDetails.jade
client/views/events/eventFiltration.jade
client/views/events/smartEvent/editSmartEventDetailsModal.jade
imports/schemas/smartEvent.coffee
imports/stylesheets/events/eventFiltration.import.styl
imports/utils.coffee
methods/promedPosts.coffee
server/autoprocess.coffee
server/publications.coffee
server/startup.coffee
server/updateAutoEvents.coffee

Pivotal story: https://www.pivotaltracker.com/story/show/150920423
This also places a limit on the number of incidents that can be published, and removes the "Select All" locations button from the filter panel because the "Deselect All" button has an equivalent effect on the filter.

Add species filter to Event pages and smart events

---

.config/chimp.js
.scripts/gen_region_to_countries.py
client/controllers/events/eventResolvedIncidents.coffee
imports/countryISOToGeoname.json
imports/incidentResolution/convertAllIncidentsToDifferentials.coffee
imports/incidentResolution/incidentResolution.coffee
imports/nlp.test.coffee
run-tests.sh
server/router.coffee
tests/features/step_definitions/incidents_steps.coffee

Aggregating cases by multiple country regions is undesirable when rendering maps. It may unnecessarily hide hotspots at the country level, regions may overlap creating inconsistencies in the overlapping area, and our contour data is for countries. To avoid these issues, this adds an option to the incident resolution code to replace incidents locations that reference a region with all the countries contained in that region. Note that our region data is for the most part limited to continents.

Add incident resolver option to convert regions into countries

---

client/controllers/events/eventFiltration.coffee
imports/incidentResolution/LocationTree.coffee
imports/incidentResolution/convertAllIncidentsToDifferentials.coffee
imports/incidentResolution/incidentResolution.coffee
imports/incidentResolution/resolver.test.coffee
imports/schemas/geoname.coffee
server/router.coffee
server/syncStructuredFeeds.coffee
server/updateAutoEvents.coffee

- When an event has multiple diseases each one is supplemented separately.
- Supplemental incidents are created for time spans that have no base incidents.
- Cumulative counts are used as constraining incidents to remove outliers.
- When there is insufficient data to do statistical outlier removal on a location, data from parent locations is used.

Outlier removal and supplemental incident improvements
